---
title: "Determinantes del Ingreso"
author: "Lehyton Arenas"
date: "12/21/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Año 2017: Estadísticos descriptivos

```{r Inicial: Librerías y Data, include=FALSE}
# Librerías a usar:
library(tidyverse)
library(plyr); library(dplyr)
library(writexl) 
library(readxl)
DataAnio_2017 <- read_excel("/Users/lehyton/Google Drive/Ecsim/Proyecto Agosto/3_Entregables Lehyton/Data/DataAnio_2017_v3.xlsx")
```

A continuación se exponen los principales descriptivos para el año 2017: 

```{r Descriptivos: Cuartiles, echo=FALSE}
DataAnio_2017_v2 <- DataAnio_2017 %>% 
  select(.,-c("AREA","ID","fex_c_2011"))

Descriptivos <- as.data.frame(do.call(rbind,lapply(DataAnio_2017_v2[,1:2]
                                                            ,summary)))

Desviacion <- as.data.frame(do.call(rbind,lapply(DataAnio_2017_v2[,1:2]
                                                            ,sd)))
  knitr::kable(
  Descriptivos,
  caption = "Resumen estadístico"
)
  knitr::kable(
  Desviacion,
  caption = "SD"
)
```
Otra forma de ver descriptivos:
```{r Descriptivos: Cuartiles, echo=FALSE}

DataAnio_2017_v2 <- DataAnio_2017 %>% 
  select(.,c("Sexo","Edad","AniosEscolaridad"))

summ1 <- DataAnio_2017_v2 %>% 
  dplyr::summarise(across(.fns = function(x){
    y <- summary(x); z <- sd(x); round(c(y,z), 2) 
    } ))
summ1 <- t(summ1)
colnames(summ1) <- c("Min", "1st_Q", "Median", "Mean", "3rd_Q", "Max", "St_d")
View(summ1)

summ2 <- as.data.frame(t(summary(DataAnio_2017_v2)))
summ2$Estadistico <- as.factor(substr(summ2$Freq,start = 1,stop = 7))
summ2$Valor <- as.numeric(substr(summ2$Freq,start = 9,stop = 13))
summ2 <- summ2 %>% select(-Var2)
View(summ2 %>% spread(value = Valor,key = Estadistico))

# Esta opción está perfecta. Solo falta agregar SD y crear el df:
summ2 <- as.data.frame(t(summary(DataAnio_2017_v2)))
summ2$Medida <- as.factor(substr(summ2$Freq,start = 1,stop = 7))
summ2$Freq<- as.numeric(substr(summ2$Freq,start = 9,stop = 13))
summ2 <- summ2 %>% select(-Var2)
View(summ2 %>% spread(value = Freq,key = Medida))
```
## Año 2017: Información por ciudad

La data recopilada se ha agrupado por ciudad y se han encontrado algunos resultados:
```{r Ciudades: procesando data , include=FALSE}
# Ciudades: Calculamos algunas medias:

# Ingreso medio por ciudad: para toda la población
# Años de escolaridad media por ciudad:
EducacionCiudades_2017 <- DataAnio_2017 %>% 
  dplyr::filter(.,is.na(AniosEscolaridad)==FALSE) %>%
  group_by(AREA) %>% 
  dplyr::summarise(
    Sum_WiXi_Educacion = round(sum(AniosEscolaridad*fex_c_2011,na.rm = TRUE),0),
    Sum_Wi = round(sum(fex_c_2011,na.rm = TRUE),0),
    EducacionMedia = round(Sum_WiXi_Educacion/Sum_Wi,0),
  ) %>% 
  dplyr::select(.,c("AREA","EducacionMedia"))

IngresoCiudades_2017 <- DataAnio_2017 %>% 
  dplyr::filter(.,is.na(IngresoLaboral_Mes)==FALSE) %>%
  group_by(AREA) %>% 
  dplyr::summarise(
    Sum_WiXi_Ingreso = round(sum(IngresoLaboral_Mes*fex_c_2011,na.rm = TRUE),0),
    Sum_Wi = round(sum(fex_c_2011,na.rm = TRUE),0),
    IngresoMedio = round(Sum_WiXi_Ingreso/Sum_Wi,0),
  ) %>% 
  dplyr::select(.,c("AREA","IngresoMedio"))

# Ingreso medio por ciudad: Solo para autoempleados
IngAutoempleados_Ciudades_2017 <- DataAnio_2017 %>% 
  dplyr::filter(.,Autoempleado==1 & is.na(IngresoLaboral_Mes)==FALSE) %>% 
  group_by(AREA) %>% 
  dplyr::summarise(
    Sum_WiXi_Ingreso = round(sum(IngresoLaboral_Mes*fex_c_2011,na.rm = TRUE),0),
    Sum_Wi = round(sum(fex_c_2011,na.rm = TRUE),0),
    IngresoAutoempleados = round(Sum_WiXi_Ingreso/Sum_Wi,0),
  ) %>% 
  dplyr::select(.,c("AREA","IngresoAutoempleados"))

# Ingreso medio por ciudad: Solo para Generadores
IngGeneradores_Ciudades_2017 <- DataAnio_2017 %>% 
  dplyr::filter(.,GeneradorEmpleo==1 & is.na(IngresoLaboral_Mes)==FALSE) %>% 
  group_by(AREA) %>% 
  dplyr::summarise(
    Sum_WiXi_Ingreso = round(sum(IngresoLaboral_Mes*fex_c_2011,na.rm = TRUE),0),
    Sum_Wi = round(sum(fex_c_2011,na.rm = TRUE),0),
    IngresoGeneradores = round(Sum_WiXi_Ingreso/Sum_Wi,0),
  ) %>% 
  dplyr::select(.,c("AREA","IngresoGeneradores"))

# Join para tener data por ciudad:
Ciudades_2017 <- join_all(list(EducacionCiudades_2017,IngresoCiudades_2017,IngAutoempleados_Ciudades_2017,IngGeneradores_Ciudades_2017), by=c("AREA"),type = "full")

```

```{r Ciudades: Creando DF, echo=FALSE}
library(knitr)
knitr::kable(
  Ciudades_2017,
  caption = "Ciudades"
)
```






