---
title: "Caracterización Jericó"
author: "Lehyton Arenas"
date: "3/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Directorio de trabajo:
setwd("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/1_EntregablesLehyton")

# Paquetes a usar
library(tidyverse)
library(plyr); library(dplyr)
library(readxl)
library(writexl)
library(survey)
```

## Caracterización Microdata ECVD2019: con FExp

```{r Data ECVD2019}
#### Data original ####

# Datas iniciales de ECV Antioquia 2019:
PersAntioquia <- read.csv("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/3_InsumosDiego&Otros/ECV2019_v2_Planeacion/ECV2019_Personas_Anonimizada.csv",sep = ";", header = TRUE, dec = ",")

ECVHogares <- read.csv("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/3_InsumosDiego&Otros/ECV2019_v2_Planeacion/ECV2019_Hogares_Anonimizada.csv",sep = ";", header = TRUE, dec = ",")

#### DFs por subpoblaciones #### 
# Se puede aplicar el mismo procedimiento para individuos y hogares.

# Agregamos dos columnas para filtrar por Eje y departamento
PersAntioquia$Eje=c("Eje")
PersAntioquia$Departamento=c("Departamento de Antioquia")

# Ahora transformamos los ejes según nuestro interés: Cartama y AMVA:
PersAntioquia <- PersAntioquia %>% 
  dplyr::mutate(Eje=ifelse(NomMpio=="Caramanta","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Concordia","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Fredonia","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Hispania","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Jericó","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="La Pintada","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Pueblorrico","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Salgar","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Támesis","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Tarso","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Valparaíso","Provincia del Cartama",Eje),
                Eje=ifelse(NomMpio=="Venecia","Provincia del Cartama",Eje),
                Eje=ifelse(NombreSubregion=="Área Metropolitana","Valle de Aburrá",Eje)
                )

# Traemos solo población de Medellín: Individuos
PersMedellin <- PersAntioquia %>% 
  dplyr::filter(NomMpio=="Medellín")

# Traemos solo población de la Provincia del Cartama: Individuos
PersCartama <- PersAntioquia %>% 
  dplyr::filter(Eje=="Provincia del Cartama")

# Traemos solo población del Valle de Aburra: Individuos
PersAMVA <- PersAntioquia %>% 
  dplyr::filter(Eje=="Valle de Aburrá")


#### Data Tipo Svy #### 

# Creamos objeto tipo Svy para AMVA: Individuos
Svy_AMVA <- svydesign(ids=~0,weights=~FexpHog,
                                  data=PersAMVA)

# Creamos objeto tipo Svy para Antioquia: Individuos
Svy_Antioquia <- svydesign(ids=~0,weights=~FexpHog,
                                  data=PersAntioquia)

# Creamos objeto tipo Svy para Cartama: Individuos
Svy_Cartama <- svydesign(ids=~0,weights=~FexpHog,
                                  data=PersCartama)

# Creamos objeto tipo Svy para Medellin: Individuos
Svy_Medellin <- svydesign(ids=~0,weights=~FexpHog,
                                  data=PersMedellin)


#### Algunos cálculos ####

# Creamos el total de población en cada municipio del Cartama:
TotalMcipio <- svytotal(~NomMpio,design = Svy_Cartama, na = TRUE)

TotalMcipio <- as.data.frame(TotalMcipio) %>% 
  dplyr::select(.,-c("SE")) %>% 
  dplyr::rename(PoblacionTotal=total)

Municipios <- c("Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia")

TotalMcipio_v2 <- data.frame(Municipios,TotalMcipio)
rm(TotalMcipio,Municipios)
# Creamos el total de población en todo Cartama:
PoblacionTotal=sum(TotalMcipio_v2$PoblacionTotal) 
Municipios <- c("Provincia del Cartama")
TotalCartama_v2 <- data.frame(Municipios,PoblacionTotal)
rm(PoblacionTotal,Municipios)

# Creamos el total de población para todo el departamento de Antioquia:
TotalAntioquia <- svytotal(~NomMpio,design = Svy_Antioquia, na = TRUE)
TotalAntioquia <- as.data.frame(TotalAntioquia) %>% 
  dplyr::select(.,-c("SE")) %>% 
  dplyr::rename(PoblacionTotal=total)

PoblacionTotal=sum(TotalAntioquia$PoblacionTotal)
Municipios <- c("Departamento de Antioquia")

TotalAntioquia_v3 <- data.frame(Municipios,PoblacionTotal)
rm(TotalAntioquia,PoblacionTotal,Municipios)

# Creamos el total de población para todo el AMVA:
TotalAMVA <- svytotal(~NomMpio,design = Svy_AMVA, na = TRUE)
TotalAMVA_v2 <- as.data.frame(TotalAMVA) %>% 
  dplyr::select(.,-c("SE")) %>% 
  dplyr::rename(PoblacionTotal=total)

Municipios <- c("Barbosa","Bello","Caldas","Copacabana","Envigado","Girardota",
                "Itagüí","La Estrella","Medellín","Sabaneta")

TotalAMVA_v3 <- data.frame(Municipios,TotalAMVA_v2)
PoblacionTotal <- sum(TotalAMVA_v3$PoblacionTotal)
Municipios <- c("Valle de Aburrá")

TotalAMVA_v5 <- data.frame(Municipios,PoblacionTotal)

rm(TotalAMVA,TotalAMVA_v2,PoblacionTotal,Municipios)

# Creamos el total de población para todo Medellín:
TotalMedellin <- TotalAMVA_v3 %>% 
  dplyr::filter(Municipios=="Medellín")
rm(TotalAMVA_v3)

# Concatenamos los totales y tenemos:
TotalPersonas <- join_all(list(TotalMcipio_v2,TotalCartama_v2,TotalAntioquia_v3,TotalAMVA_v5,TotalMedellin), by=c("Municipios"),type = "full")

rm(TotalAMVA_v5,TotalAntioquia_v3,TotalCartama_v2,TotalMcipio_v2,TotalMcipio_v2,TotalMedellin)
```

```{r Educación}
#### Tema: Condición educativa ####
# Pregunta data: "P_043"
# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_043, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_043, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_043, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_043, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_043, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

Proporciones <- join_all(list(TotalSubt,TotalPersonas),by=c("Municipios"),type = "full")

Proporciones <- Proporciones %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/PoblacionTotal)*100,2),
                P_043=ifelse(P_043==1,"Presencial",P_043),
                P_043=ifelse(P_043==2,"Virtual",P_043),
                P_043=ifelse(P_043==3,"No estudia",P_043)
                )
# Paso opcional: poner data en factores para un orden establecido:
Proporciones$Municipios <- factor(Proporciones$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Graficamos:
ggplot(Proporciones, aes(x = Porcentaje, y = Municipios, fill=P_043))+
  geom_col(position="dodge")+
  labs(x="Porcentaje",y="Municipios",fill="Condición de estudio:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.2, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical"
        )+
  scale_x_continuous(limits=c(0,80))

# Paso opcional: exportamos data:
write_xlsx(Proporciones, "Proporciones.xlsx")

# Eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,Proporciones)

#### Tema: Causa para no continuar estudios. ####
# Pregunta data: : P:046
# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_046, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(.,P_046!="-99",P_046!="-88")

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_046, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(.,P_046!="-99",P_046!="-88")
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_046, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(.,P_046!="-99",P_046!="-88")

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_046, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(.,P_046!="-99",P_046!="-88")

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_046, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(.,P_046!="-99",P_046!="-88")

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:
TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_046=="1","No está en edad escolar",Columna),
                Columna=ifelse(P_046=="2","Ya terminó",Columna),
                Columna=ifelse(P_046=="3","Costos educativos",Columna),
                Columna=ifelse(P_046=="4","Oficios del hogar",Columna),
                Columna=ifelse(P_046=="5","Falta de tiempo",Columna),
                Columna=ifelse(P_046=="6","Embarazo",Columna),
                Columna=ifelse(P_046=="7","Inseguridad",Columna),
                Columna=ifelse(P_046=="8","Falta de cupos",Columna),
                Columna=ifelse(P_046=="9","No hay centro educativo",Columna),
                Columna=ifelse(P_046=="10","Necesita trabajar",Columna),
                Columna=ifelse(P_046=="11","No le gusta estudiar",Columna),
                Columna=ifelse(P_046=="12","Enfermedad",Columna),
                Columna=ifelse(P_046=="13","Necesita educación especial",Columna),
                Columna=ifelse(P_046=="14","Malos tratos en colegio",Columna),
                Columna=ifelse(P_046=="15","Se casó o formó pareja",Columna),
                Columna=ifelse(P_046=="16","Abandono de residencia",Columna),
                Columna=ifelse(P_046=="17","Bajo rendimiento",Columna),
                Columna=ifelse(P_046=="18","No tiene documentos necesarios",Columna),
                Columna=ifelse(P_046=="19","Razones familiares",Columna),
                Columna=ifelse(P_046=="20","Servicio militar",Columna),
                Columna=ifelse(P_046=="21","No responde",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )
# hacemos una prueba para validar el caso de Jericó:
Prueba <- TotalSubt_v3 %>% 
  dplyr::filter(Municipios=="Jericó")

# Graficamos:
ggplot(Prueba,aes(x=Porcentaje,y=reorder(Columna,-Porcentaje)))+
  geom_col(fill="aquamarine3")+
  labs(x="Porcentaje",y="Jericó: Causas de no estudiar")+
  geom_text(aes(label = Porcentaje),position = position_stack(1),
            size=4, vjust=0.5, hjust=-0.1 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)))+
  scale_x_continuous(limits=c(0,60))

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "CausaNoEstudiar.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3,Prueba)

#### Tema: Ultimo nivel de estudios. ####
# Pregunta data: : P:049
# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_049, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_049, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_049, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_049, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_049, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))


# Recodificamos y encontramos proporciones:

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_049==0,"Ninguno",Columna),
                Columna=ifelse(P_049==1,"Preescolar",Columna),
                Columna=ifelse(P_049==2,"Primaria",Columna),
                Columna=ifelse(P_049==3,"Secundaria",Columna),
                Columna=ifelse(P_049==4,"Media",Columna),
                Columna=ifelse(P_049==5,"Técnico",Columna),
                Columna=ifelse(P_049==6,"Tecnológico",Columna),
                Columna=ifelse(P_049==7,"Pregrado",Columna),
                Columna=ifelse(P_049==8,"Especialización",Columna),
                Columna=ifelse(P_049==9,"Maestría",Columna),
                Columna=ifelse(P_049==10,"Doctorado",Columna)
                )

# Concatenamos con el total de población:
TotalSubt_v2 <- join_all(list(TotalPersonas,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v2 <- TotalSubt_v2 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/PoblacionTotal)*100,2)
                )

# hacemos una prueba para validar el caso de Jericó:
Prueba <- TotalSubt_v2 %>% 
  dplyr::filter(Municipios=="Jericó")

# Graficamos:
ggplot(Prueba,aes(x=Porcentaje,y=Columna))+
  geom_col(fill="coral")+
  labs(x="Porcentaje",y="Jericó: Ultimo nivel de estudios")+
  geom_text(aes(label = Porcentaje),position = position_stack(1),
            size=4, vjust=0.5, hjust=-0.1 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)))+
  scale_x_continuous(limits=c(0,35))

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v2, "NivelEstudios.xlsx")

# eliminamos:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,Prueba)

#### Tema: Area del conocimiento.  ####
# Pregunta data: : P:052
# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_052, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_052!="-98",P_052!="-99",P_052!="-88")

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_052, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(P_052!="-98",P_052!="-99",P_052!="-88")
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_052, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_052!="-98",P_052!="-99",P_052!="-88")

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_052, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_052!="-98",P_052!="-99",P_052!="-88")

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_052, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_052!="-98",P_052!="-99",P_052!="-88")

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificar variable: 

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_052==1,"Agronomia y afines",Columna),
                Columna=ifelse(P_052==2,"Bellas Artes",Columna),
                Columna=ifelse(P_052==3,"Ciencias de la Educación",Columna),
                Columna=ifelse(P_052==4,"Ciencias de la Salud",Columna),
                Columna=ifelse(P_052==5,"Ciencias Sociales y afines",Columna),
                Columna=ifelse(P_052==6,"Economia y afines",Columna),
                Columna=ifelse(P_052==7,"Humanidades y religiosas",Columna),
                Columna=ifelse(P_052==8,"Ing. Sistemas y afines",Columna),
                Columna=ifelse(P_052==9,"Ing. Industrial y afines",Columna),
                Columna=ifelse(P_052==10,"Ing. Electrónica y afines",Columna),
                Columna=ifelse(P_052==11,"Ing. Mecánica y afines",Columna),
                Columna=ifelse(P_052==12,"Ing. Ambiental y afines",Columna),
                Columna=ifelse(P_052==13,"Ing. Química y afines ",Columna),
                Columna=ifelse(P_052==14,"Ing. Civil y afines",Columna),
                Columna=ifelse(P_052==15,"Matemáticas y C. Naturales",Columna),
                Columna=ifelse(P_052==16,"Otras",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )
# hacemos una prueba para validar el caso de Jericó:
Prueba <- TotalSubt_v3 %>% 
  dplyr::filter(Municipios=="Jericó")

# Graficamos:
ggplot(Prueba,aes(x=Porcentaje,y=reorder(Columna,-Porcentaje)))+
  geom_col(fill="aquamarine3")+
  labs(x="Porcentaje",y="Jericó: Causas de no estudiar")+
  geom_text(aes(label = Porcentaje),position = position_stack(1),
            size=4, vjust=0.5, hjust=-0.1 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)))+
  scale_x_continuous(limits=c(0,60))

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "12_AreaConocimiento.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3,Prueba)

```

```{r Seguridad social}
#### Tema: Afiliaciones Pensiones y ARL. ####

# Paso 1: Calculamos los Ocupaddos por localizaación: 

# Calculamos el total de Ocupados para Provincia+AMVA+Antioquia.:
# Usamos la metoddología de la ficha de Planeación
Ocu_Antioquia <- PersAntioquia %>% 
  dplyr::filter((Zona==1 & P_021>=12) | (Zona==2 & P_021>=10),
                (P_077==1 | P_080==1 | P_081==1 | P_082==1)) 

# Transformamos los ocupados en Svy
OcuAntio_Svy <- svydesign(ids=~0,weights=~FexpPer_EQ,
                                  data=Ocu_Antioquia)

# Calculamos total Ocupados para Provincia+AMVA+Antioquia.
Ocupados_Antio <- svytotal(~Eje,design=OcuAntio_Svy,na=TRUE)

Ocupados_Antio <- as.data.frame(Ocupados_Antio) %>% 
  dplyr::select(.,-c("SE")) %>% 
  dplyr::rename(OcupadosTotal=total)

Municipios <- c("Eje","Provincia del Cartama","Valle de Aburrá")

Ocupados_Antio_v2 <- data.frame(Municipios,Ocupados_Antio)

Antioquia = sum(Ocupados_Antio_v2$OcupadosTotal)

z <- data.frame(Municipios=c("Departamento de Antioquia"),
                OcupadosTotal=Antioquia)

Ocupados_Antio_v3 <- rbind(Ocupados_Antio_v2,z) %>% 
  dplyr::filter(Municipios!="Eje")
# Eliminamos intermedios
rm(Ocu_Antioquia,OcuAntio_Svy,Ocupados_Antio,Municipios,Ocupados_Antio_v2,Antioquia,z)

# Hacemos los pasos anteriores para Medellín y Municipios de Cartama:
Subtotal <- PersAntioquia %>% 
  dplyr::filter(NomMpio=="Caramanta" | NomMpio=="Concordia" |
                NomMpio=="Fredonia" |
                NomMpio=="Hispania" |
                NomMpio=="Jericó"|
                NomMpio=="La Pintada"|
                NomMpio=="Pueblorrico"|
                NomMpio=="Salgar"|
                NomMpio=="Támesis"|
                NomMpio=="Tarso"|
                NomMpio=="Valparaíso"|
                NomMpio=="Venecia"|
                NomMpio=="Medellín")
# Se encuentran ocupados siguiendo psos de ficha técnica:
Ocu_Subtotal <- Subtotal %>% 
  dplyr::filter((Zona==1 & P_021>=12) | (Zona==2 & P_021>=10),
                (P_077==1 | P_080==1 | P_081==1 | P_082==1))

# Transformamos los ocupados en Svy
OcuSubtotal_Svy <- svydesign(ids=~0,weights=~FexpPer_EQ,
                                  data=Ocu_Subtotal)

# Calculamos total Ocupados para Medellín y Mpios Cartama.
Ocupados_Subto <- svytotal(~NomMpio,design=OcuSubtotal_Svy,na=TRUE)

Ocupados_Subto <- as.data.frame(Ocupados_Subto) %>% 
  dplyr::select(.,-c("SE")) %>% 
  dplyr::rename(OcupadosTotal=total)

Municipios <- c("Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Medellín","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia")

Ocupados_Subto_v2 <- data.frame(Municipios,Ocupados_Subto)

# Concatenamos todo
Ocupados <- rbind(Ocupados_Antio_v3,Ocupados_Subto_v2)

# Eliminamos intermedios
rm(Ocupados_Antio_v3,Subtotal,Ocu_Subtotal,OcuSubtotal_Svy,Ocupados_Subto,Municipios,Ocupados_Subto_v2)

# Paso 2: Encontramos el total de Pensiones:
# Pregunta data: "P_075"

# Calculamos total Ocupados para  cada localizacion.
Pens_Antioq <- as.data.frame(svytable(~Departamento+P_075, design=Svy_Antioquia)) %>% 
  dplyr::rename(Municipios=Departamento,PensionesCol=Freq) %>% 
  dplyr::filter(P_075==1)

Pens_Ejes <- as.data.frame(svytable(~Eje+P_075, design=Svy_Antioquia)) %>% 
  dplyr::rename(Municipios=Eje,PensionesCol=Freq) %>% 
  dplyr::filter(P_075==1,
                Municipios!="Eje")

Pens_Medellin <- as.data.frame(svytable(~NomMpio+P_075, design=Svy_Medellin)) %>% 
  dplyr::rename(Municipios=NomMpio,PensionesCol=Freq) %>% 
  dplyr::filter(P_075==1)

Pens_MpiosCartama <- as.data.frame(svytable(~NomMpio+P_075, design=Svy_Cartama)) %>% 
  dplyr::rename(Municipios=NomMpio,PensionesCol=Freq) %>% 
  dplyr::filter(P_075==1)

# Concatenamos:
Pensiones <- rbind(Pens_Antioq,Pens_Ejes,Pens_Medellin,Pens_MpiosCartama) %>% dplyr::select(Municipios,PensionesCol)

# Eliminamos intermedios:
rm(Pens_Antioq,Pens_Ejes,Pens_Medellin,Pens_MpiosCartama)

# Paso 3: Encontramos el total de ARL:
# Pregunta data: "P_076"

# Calculamos total Ocupados para  cada localizacion.
ARL_Antioq <- as.data.frame(svytable(~Departamento+P_076, design=Svy_Antioquia)) %>% 
  dplyr::rename(Municipios=Departamento,ARLCol=Freq) %>% 
  dplyr::filter(P_076==1)

ARL_Ejes <- as.data.frame(svytable(~Eje+P_076, design=Svy_Antioquia)) %>% 
  dplyr::rename(Municipios=Eje,ARLCol=Freq) %>% 
  dplyr::filter(P_076==1,
                Municipios!="Eje")

ARL_Medellin <- as.data.frame(svytable(~NomMpio+P_076, design=Svy_Medellin)) %>% 
  dplyr::rename(Municipios=NomMpio,ARLCol=Freq) %>% 
  dplyr::filter(P_076==1)

ARL_MpiosCartama <- as.data.frame(svytable(~NomMpio+P_076, design=Svy_Cartama)) %>% 
  dplyr::rename(Municipios=NomMpio,ARLCol=Freq) %>% 
  dplyr::filter(P_076==1)

# Concatenamos:
ARL <- rbind(ARL_Antioq,ARL_Ejes,ARL_Medellin,ARL_MpiosCartama) %>% dplyr::select(Municipios,ARLCol)

# Eliminamos intermedios:
rm(ARL_Antioq,ARL_Ejes,ARL_Medellin,ARL_MpiosCartama)

# Paso 4: Concatenamos: Ocupados, Pension y ARL:
Afiliaciones <- join_all(list(Ocupados,Pensiones,ARL), by=c("Municipios"),type = "full") %>% 
  dplyr::mutate(PorcPensiones=round((PensionesCol/OcupadosTotal)*100,2),
                PorcARL=round((ARLCol/OcupadosTotal)*100,2))%>% 
  dplyr::select(.,c("Municipios","PorcPensiones","PorcARL")) %>% 
  dplyr::rename(Pensiones=PorcPensiones,ARL=PorcARL)

# Paso opcional: poner data en factores para un orden establecido:
Afiliaciones$Municipios <- factor(Afiliaciones$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Pasamos a formato largo
Afiliaciones2 <- Afiliaciones %>% 
  gather("Afiliacion", value= "Porcentaje",c("Pensiones","ARL"))

# Paso 5: Graficamos:
ggplot(Afiliaciones2, aes(x=Porcentaje,y=Municipios,fill=Afiliacion))+
  geom_col(position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Afiliación:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top")+
  scale_x_continuous(limits=c(0,75))

# Paso opcional: exportamos data:
write_xlsx(Afiliaciones, "14_Afiliaciones.xlsx")

# eliminamos intermedios:
rm(Ocupados,Pensiones,ARL,Afiliaciones,Afiliaciones2)
```

```{r Mercado laboral}
#### Tema: Actividad última semana. ####
# Pregunta data: : P_077
# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_077, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_077!="-98",P_077!="-99",P_077!="-88")

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_077, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(P_077!="-98",P_077!="-99",P_077!="-88")
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_077, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_077!="-98",P_077!="-99",P_077!="-88")

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_077, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_077!="-98",P_077!="-99",P_077!="-88")

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_077, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_077!="-98",P_077!="-99",P_077!="-88")

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:
TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_077==1,"Trabajando",Columna),
                Columna=ifelse(P_077==2,"Buscando trabajo",Columna),
                Columna=ifelse(P_077==3,"Estudiando",Columna),
                Columna=ifelse(P_077==4,"Oficios del hogar",Columna),
                Columna=ifelse(P_077==5,"Rentista",Columna),
                Columna=ifelse(P_077==6,"Jubilado",Columna),
                Columna=ifelse(P_077==7,"Otra actividad",Columna),
                Columna=ifelse(P_077==8,"Incapacitado",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "26_ActividadSemana.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3)

# En este caso no sse grafica porque solo es importante sacar los datos para que Freddy haga los mapas.

#### Tema: Posición ocupacional.  ####
# Pregunta data: : P_099

# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_099, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_099!="-98",P_099!="-99",P_099!="-88")

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_099, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(P_099!="-98",P_099!="-99",P_099!="-88")
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_099, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_099!="-98",P_099!="-99",P_099!="-88")

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_099, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_099!="-98",P_099!="-99",P_099!="-88")

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_099, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_099!="-98",P_099!="-99",P_099!="-88")

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_099==-77,"Otro",Columna),
                Columna=ifelse(P_099==1,"Empleado de empresa particular",Columna),
                Columna=ifelse(P_099==2,"Empleado del gobierno",Columna),
                Columna=ifelse(P_099==3,"Empleado doméstico",Columna),
                Columna=ifelse(P_099==4,"Cuenta propia",Columna),
                Columna=ifelse(P_099==5,"Empleador",Columna),
                Columna=ifelse(P_099==6,"Trabajador fliar sin remuneración",Columna),
                Columna=ifelse(P_099==7,"Trabajador sin remuneración",Columna),
                Columna=ifelse(P_099==8,"Jornalero",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "28_PosicionOcupacional.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3)

# En este caso no sse grafica porque solo es importante sacar los datos para que Freddy haga los mapas.

#### Tema: Sector económico empresa. ####
# Pregunta data: : P_096

# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_096, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_096!="-98",P_096!="-99",P_096!="-88")

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_096, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(P_096!="-98",P_096!="-99",P_096!="-88")
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_096, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_096!="-98",P_096!="-99",P_096!="-88")

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_096, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_096!="-98",P_096!="-99",P_096!="-88")

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_096, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_096!="-98",P_096!="-99",P_096!="-88")

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_096==1,"Agropecuaria, silvicultura y pesca",Columna),
                Columna=ifelse(P_096==2,"Minería",Columna),
                Columna=ifelse(P_096==3,"Electricidad, gas, agua",Columna),
                Columna=ifelse(P_096==4,"Industria",Columna),
                Columna=ifelse(P_096==5,"Construcción",Columna),
                Columna=ifelse(P_096==6,"Comercio, hotel, restaurantes",Columna),
                Columna=ifelse(P_096==7,"Transporte, almacenamiento y comunicaciones",Columna),
                Columna=ifelse(P_096==8,"Estab. Financieros, inmuebles y otros",Columna),
                Columna=ifelse(P_096==9,"Servicios sociales, comunales y personales",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "29_SectorLaboral.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3)

# En este caso no se grafica porque solo es importante sacar los datos para que Freddy haga los mapas.

```

```{r Proyectos productivos}
#### Tema: Tenencia negocio. ####
# Pregunta data: P_290

# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_290, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_290, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_290, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_290, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_290, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_290==1,"Si",Columna),
                Columna=ifelse(P_290==2,"No",Columna),
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )

# Graficamos:
ggplot(TotalSubt_v3, aes(x = Porcentaje, y = Municipios, fill=Columna))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Tiene negocio:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.9),
            size=4, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.3)),
        legend.text=element_text(size=rel(1.3)),
        legend.position="top")+
  scale_x_continuous(limits=c(0,100))

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "33_HogaresNegocio.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3)

#### Tema: Sector económico Negocio. ####
# Pregunta data: : P_291

# Creamos subtotales para cada localización de interés:
Subt_AMVA <- as.data.frame(svytable(~Eje+P_291, design = Svy_AMVA)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_291!=-99,P_291!=-88,P_291!=-98)

Subt_Antioquia <- as.data.frame(svytable(~Departamento+P_291, design = Svy_Antioquia)) %>%
  dplyr::rename(Municipios=Departamento,Subtotal=Freq)%>% 
  dplyr::filter(P_291!=-99,P_291!=-88,P_291!=-98)
 
Subt_Cartama <- as.data.frame(svytable(~Eje+P_291, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=Eje,Subtotal=Freq)%>% 
  dplyr::filter(P_291!=-99,P_291!=-88,P_291!=-98)

Subt_CartMpios <- as.data.frame(svytable(~NomMpio+P_291, design = Svy_Cartama)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_291!=-99,P_291!=-88,P_291!=-98)

Subt_Medellin <- as.data.frame(svytable(~NomMpio+P_291, design = Svy_Medellin)) %>%
  dplyr::rename(Municipios=NomMpio,Subtotal=Freq)%>% 
  dplyr::filter(P_291!=-99,P_291!=-88,P_291!=-98)

# Conacatenamos
TotalSubt <- join_all(list(Subt_CartMpios,Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_Medellin),by=c("Municipios"),type = "full")

# Paso opcional: poner data en factores para un orden establecido:
TotalSubt$Municipios <- factor(TotalSubt$Municipios, levels=c("Departamento de Antioquia","Valle de Aburrá","Medellín","Provincia del Cartama","Caramanta","Concordia","Fredonia","Hispania","Jericó","La Pintada","Pueblorrico","Salgar","Támesis","Tarso","Valparaíso","Venecia"
))

# Recodificamos variables:

TotalSubt$Columna <- c("Columna")

TotalSubt <- TotalSubt %>% 
  dplyr::mutate(Columna=ifelse(P_291==1,"Agropecuaria, silvicultura y pesca",Columna),
                Columna=ifelse(P_291==2,"Minería",Columna),
                Columna=ifelse(P_291==3,"Electricidad, gas, agua",Columna),
                Columna=ifelse(P_291==4,"Industria",Columna),
                Columna=ifelse(P_291==5,"Construcción",Columna),
                Columna=ifelse(P_291==6,"Comercio, hotel, restaurantes",Columna),
                Columna=ifelse(P_291==7,"Transporte, almacenamiento y comunicaciones",Columna),
                Columna=ifelse(P_291==8,"Estab. Financieros, inmuebles y otros",Columna),
                Columna=ifelse(P_291==9,"Servicios sociales, comunales y personales",Columna)
                )

# Hallamos los totales por municipio:
TotalSubt_v2 <- TotalSubt %>% 
  dplyr::group_by(Municipios) %>% 
  dplyr::summarise(
      Total = sum(Subtotal,na.rm = TRUE))

# Concatenamos:
TotalSubt_v3 <- join_all(list(TotalSubt_v2,TotalSubt), by=c("Municipios"),type = "full")

# Hacemos los cálculos de proporciones:
TotalSubt_v3 <- TotalSubt_v3 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2)
                )

# Paso opcional: exportamos data:
write_xlsx(TotalSubt_v3, "34_SectorNegocio.xlsx")

# eliminamos intermedios:
rm(Subt_AMVA,Subt_Antioquia,Subt_Cartama,Subt_CartMpios,Subt_Medellin,TotalSubt,TotalSubt_v2,TotalSubt_v3)

```

## Caracterización Data Primaria: sin FExp
```{r Data Primaria}
#### Datas primarias ####
# Por un error la convención de la data aparece como "Piloto...", pero no pasa nada
PilotoIndividuos <- read_excel("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/2_EntregablesOtros/9_Arbey_DataExportada/20210701_Data.xlsx",sheet="p_039")

PilotoHogares <- read_excel("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/2_EntregablesOtros/9_Arbey_DataExportada/20210701_Data.xlsx",sheet="Encuesta definitiva Jericó -...")

PilotoProyectos <- read_excel("/Volumes/Respaldo/Google Drive-Actualizado/Ecsim/2021_CaracterizaciónJericó/2_EntregablesOtros/9_Arbey_DataExportada/20210701_Data.xlsx",sheet="p_103_2")

#### Algunos cálculos propios ####

# Mejoramos la columna de localización en PilotoIndividuos:
PilotoIndividuos <- PilotoIndividuos %>% 
  dplyr::rename(Vereda="Corregimiento o vereda")

PilotoIndividuos$Localizacion <- c("Localización")

PilotoIndividuos <- PilotoIndividuos %>%
  dplyr::mutate(Localizacion=ifelse(is.na(Vereda)==T,"Cabecera Urbana",Vereda))

# Mejoramos la columna de localización en PilotoHogares:
PilotoHogares <- PilotoHogares %>% 
  dplyr::rename(Vereda="Corregimiento o vereda")

PilotoHogares$Localizacion <- c("Localización")

PilotoHogares <- PilotoHogares %>%
  dplyr::mutate(Localizacion=ifelse(is.na(Vereda)==T,"Cabecera Urbana",Vereda))

# Mejoramos la columna de localización en PilotoProyectos:
PilotoProyectos <- PilotoProyectos %>% 
  dplyr::rename(Vereda="Corregimiento o vereda")

PilotoProyectos$Localizacion <- c("Localización")

PilotoProyectos <- PilotoProyectos %>%
  dplyr::mutate(Localizacion=ifelse(is.na(Vereda)==T,"Cabecera Urbana",Vereda))

#### Funciones ####
# Función para: Piloto Individuos
# Función agrupa: toma una data, la agrupa según la columna y calcula los %
Agrupa <- function(Data,Columna){
  
  Data_v2 <- Data %>%
  dplyr::group_by(Localizacion) %>%
  dplyr::summarise(
    TotalLocalizacion = n())
  
  Data_v3 <- Data %>%
  dplyr::group_by(Localizacion,{{Columna}}) %>%
  dplyr::summarise(
    Subtotal = n())

  Data_v4 <- join_all(list(Data_v2,Data_v3), by=c("Localizacion"),type = "full")

  Data_v4 <- Data_v4 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/TotalLocalizacion)*100,2))

return(Data_v4)
}
```

```{r Modulo Características del hogar}
#### Tema: Edad ####
# Pregunta data: "Edad de ${p_040}:"

Edades <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"Edad de ${p_040}:")) %>%
  dplyr::rename(Edad="Edad de ${p_040}:")%>% 
  dplyr::filter(is.na(Edad)==F,
                Edad>0) # eliminamos valores negativos

# Transformamos data a tipo numérico
Edades$Edad <- as.numeric(Edades$Edad)

# Creamos DF: con promedios de tiempo por localización:

Edades_v2 <- Edades %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      Tiempo = round(mean(Edad,na.rm = TRUE),2)
      )

# Graficamos:
ggplot(Edades_v2, aes(x=Tiempo,y=Localizacion))+
  geom_bar(stat="identity", position="dodge",fill="cyan4")+
  labs(x="Edad (promedio)",y="Localización")+
  geom_text(aes(label = Tiempo),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,70))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Tiempos, "HorasTrabajo.xlsx")

# Eliminamos intermedios:
rm(Edades,Edades_v2)


#### Tema: Sexo ####
# Pregunta data: "Sexo de ${p_040}:"

Sexo <- PilotoIndividuos %>%
  dplyr::select(.,"Vereda","Localizacion","Sexo de ${p_040}:") %>%
  dplyr::rename(SexoCol="Sexo de ${p_040}:")

Sexo_v2 <- Agrupa(Data=Sexo,Columna=SexoCol)
  
# Graficamos:
ggplot(Sexo_v2, aes(x=Porcentaje,y=Localizacion,fill=SexoCol))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Sexo:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.5),
            size=4, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top")+
  scale_x_continuous(limits=c(0,100))

# Paso opcional: exportamos data:
write_xlsx(Sexo_v5, "Sexo.xlsx")

# Eliminamos intermedios:
rm(Sexo,Sexo_v2)

#### Tema: Identidad sexual ####
# Pregunta data: "${p_040} se identifica como:"
Identidad <- PilotoIndividuos %>%
  dplyr::select(.,"Vereda","Localizacion","${p_040} se identifica como:") %>%
  dplyr::rename(IdentidadCol="${p_040} se identifica como:") %>% 
  dplyr::filter(is.na(IdentidadCol)==F)

Identidad_v2 <- Agrupa(Data=Identidad,Columna=IdentidadCol)

# Graficamos:
ggplot(Identidad_v2, aes(x=Porcentaje,y=Localizacion,fill=IdentidadCol))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Identidad sexual:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(0.7)),
        legend.position="top")+
  scale_x_continuous(limits=c(0,107))

# Paso opcional: exportamos data:
write_xlsx(Identidad_v2, "Identidad.xlsx")

# Eliminamos intermedios:
rm(Identidad,Identidad_v2)

#### Tema: Medios de información####
# Preguntas data: 
#"${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador de escritorio"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador portátil"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Tableta"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Telefono celular"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Televisor"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Reproductor de radio"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Periódico"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Revistas"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Ninguno"
# "${p_040}. ¿Qué medios usa principalmente para estar informado?/Otro"

Informacion <- PilotoIndividuos %>%
  dplyr::select(.,c("Vereda","Localizacion","${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador de escritorio","${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador portátil", "${p_040}. ¿Qué medios usa principalmente para estar informado?/Tableta","${p_040}. ¿Qué medios usa principalmente para estar informado?/Telefono celular","${p_040}. ¿Qué medios usa principalmente para estar informado?/Televisor","${p_040}. ¿Qué medios usa principalmente para estar informado?/Reproductor de radio","${p_040}. ¿Qué medios usa principalmente para estar informado?/Periódico","${p_040}. ¿Qué medios usa principalmente para estar informado?/Revistas","${p_040}. ¿Qué medios usa principalmente para estar informado?/Ninguno","${p_040}. ¿Qué medios usa principalmente para estar informado?/Otro")) %>%
  dplyr::rename(Computador="${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador de escritorio",Portatil="${p_040}. ¿Qué medios usa principalmente para estar informado?/Computador portátil",Tablet="${p_040}. ¿Qué medios usa principalmente para estar informado?/Tableta",Celular="${p_040}. ¿Qué medios usa principalmente para estar informado?/Telefono celular",Televisor="${p_040}. ¿Qué medios usa principalmente para estar informado?/Televisor",Radio="${p_040}. ¿Qué medios usa principalmente para estar informado?/Reproductor de radio",Periodico="${p_040}. ¿Qué medios usa principalmente para estar informado?/Periódico",Revistas="${p_040}. ¿Qué medios usa principalmente para estar informado?/Revistas",Ninguno="${p_040}. ¿Qué medios usa principalmente para estar informado?/Ninguno",Otro="${p_040}. ¿Qué medios usa principalmente para estar informado?/Otro")

# Volvemos todas las columnaas en tipo numéricas:
Informacion$Computador <- as.numeric(Informacion$Computador)
Informacion$Portatil <- as.numeric(Informacion$Portatil)
Informacion$Tablet <- as.numeric(Informacion$Tablet)
Informacion$Celular <- as.numeric(Informacion$Celular)
Informacion$Televisor <- as.numeric(Informacion$Televisor)
Informacion$Radio <- as.numeric(Informacion$Radio)
Informacion$Periodico <- as.numeric(Informacion$Periodico)
Informacion$Revistas <- as.numeric(Informacion$Revistas)
Informacion$Ninguno <- as.numeric(Informacion$Ninguno)
Informacion$Otro <- as.numeric(Informacion$Otro)

# vamos a crear subgrupos por localidad y luego se concatenan. Para esto creamos una función:
# Funcion:
# Esta función usa la data inicial y la localización que queremos usar:
AgrupaInforma <- function(Data,LocalizacionStr){
  
  DataLocaliza <- Data %>% 
  dplyr::filter(Localizacion==LocalizacionStr)

  DataLocaliza_v2 <- data.frame("Localizacion"=c(LocalizacionStr),
                      "Medio"=c("Computador","Portátil","Tablet","Celular","Televisor","Radio","Periódico","Revistas","Ninguno","Otro"),
                        "Subtotal"=colSums(DataLocaliza[,3:12], na.rm=T)
                        )

  DataLocaliza_v2$Total <- sum(DataLocaliza_v2$Subtotal)

  DataLocaliza_v2 <- DataLocaliza_v2 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2))

return(DataLocaliza_v2)
}

# Aplicamos la función en cada localización:
Cabecera <- AgrupaInforma(Data=Informacion,LocalizacionStr="Cabecera Urbana")

VdaGuacamayal <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Guacamayal")

VdaVinia <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda La Viña")

VdaPalenque <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Palenque")

VdaPalenquito <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Palenquito")

VdaQuebAlta <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Quebradona Alta")

VdaQuebBaja <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Quebradona Baja")

VdaQuebMedia <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Quebradona Media")

CorrPaloCabil <- AgrupaInforma(Data=Informacion,LocalizacionStr="Corregimiento de Palocabildo")

VdaVallecitos <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Vallecitos")

VdaHermosa <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda La Hermosa")

VdaPista <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda La Pista")

VdaCabania <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda La Cabaña")

VdaBuga <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Buga")

VdaCauca <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda Cauca")

VdaLaFe <- AgrupaInforma(Data=Informacion,LocalizacionStr="Vereda La Fe")

CorrPuenteIg <- AgrupaInforma(Data=Informacion,LocalizacionStr="Corregimiento de Puente Iglesias")

# Concatenamos la data:
Informacion_v2 <- join_all(list(Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebAlta,VdaQuebBaja,VdaQuebMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPuenteIg), by=c("Localizacion"),type = "full")

# Graficamos:
# Aunque este tipo de gráfico no es recomendabe por la cantidad de categorias:
ggplot(Informacion_v2, aes(x = Porcentaje, y = Localizacion, fill = Medio))+
  geom_bar(stat="identity",position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Medio información:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4.4, vjust=0.4, hjust=-0.05 ,col="black")+
  theme(axis.title=element_text(size=rel(1.5)),
        axis.text.x=element_text(size=rel(1.5)),
        axis.text.y=element_text(size=rel(1.5)),
        legend.title=element_text(size=rel(1.3)),
        legend.text=element_text(size=rel(1)),
        legend.position="top"
        )+
  scale_x_continuous(limits=c(0,55))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Informacion_v2, "MediosInfo.xlsx")

# Eliminamos intermedios:
rm(Informacion,Informacion_v2,Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebAlta,VdaQuebBaja,VdaQuebMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPuenteIg,AgrupaInforma)

#### Tema: Frecuencia de Medios de información ####
# Pregunta data: "${p_040}. ¿Con qué frecuencia usa este medio?"

Frecuencia <- PilotoIndividuos %>%
  dplyr::select(.,"Localizacion","${p_040}. ¿Con qué frecuencia usa este medio?") %>%
  dplyr::rename(FrecuenciaCol="${p_040}. ¿Con qué frecuencia usa este medio?") %>%
  dplyr::filter(FrecuenciaCol!="No sabe",
                is.na(FrecuenciaCol)==F)

Frecuencia_v2 <- Agrupa(Data=Frecuencia,Columna=FrecuenciaCol)
  
# Graficamos:
ggplot(Frecuencia_v2, aes(x=Porcentaje,y=Localizacion,fill=FrecuenciaCol))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Frecuencia uso:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.5),
            size=4, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,110))

# Paso opcional: exportamos data:
write_xlsx(Frecuencia_v2, "FrecuenciaUso.xlsx")

# Eliminamos intermedios:
rm(Frecuencia,Frecuencia_v2)


#### Tema: Productos financieros ####
# Preguntas data: 
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta corriente"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta de ahorros"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/CDT"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vivienda"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vehículo"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para libre inversión"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Tarjeta de crédito"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Ninguno"
# "${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Otro"

Informacion <- PilotoIndividuos %>%
  dplyr::select(.,c("Localizacion","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta corriente","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta de ahorros","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/CDT","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vivienda","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vehículo","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para libre inversión","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Tarjeta de crédito","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Ninguno","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Otro","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/No sabe","${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/No responde")) %>%
  dplyr::rename(CtaCorriente="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta corriente",CtaAhorros="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Cuenta de ahorros",CDT="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/CDT",PrestamoVivienda="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vivienda",PrestamoCarro="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para compra de vehículo",PrestamoLibre="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Préstamo para libre inversión",TarjetaCredito="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Tarjeta de crédito",Ninguno="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Ninguno",Otro="${p_040}. ¿Cuáles de los siguientes productos financieros usa principalmente?/Otro")

# Volvemos todas las columnaas en tipo numéricas:
Informacion$CtaCorriente <- as.numeric(Informacion$CtaCorriente)
Informacion$CtaAhorros <- as.numeric(Informacion$CtaAhorros)
Informacion$CDT <- as.numeric(Informacion$CDT)
Informacion$PrestamoVivienda <- as.numeric(Informacion$PrestamoVivienda)
Informacion$PrestamoCarro <- as.numeric(Informacion$PrestamoCarro)
Informacion$PrestamoLibre <- as.numeric(Informacion$PrestamoLibre)
Informacion$TarjetaCredito <- as.numeric(Informacion$TarjetaCredito)
Informacion$Ninguno <- as.numeric(Informacion$Ninguno)
Informacion$Otro <- as.numeric(Informacion$Otro)

# vamos a crear subgrupos por localidad y luego se concatenan. Para esto creamos una función:
# Funcion:
# Esta función usa la data inicial y la localización que queremos usar:
AgrupaInforma_v2 <- function(Data,LocalizacionStr){
  
  DataLocaliza <- Data %>% 
  dplyr::filter(Localizacion==LocalizacionStr)

  DataLocaliza_v2 <- data.frame("Localizacion"=c(LocalizacionStr),
                      "Medio"=c("Cta Corriente","Cta Ahorros","CDT","Prestamo Vivienda","Prestamo Carro","Prestamo Libre","Tarjeta Crédito","Ninguno","Otro"),
                        "Subtotal"=colSums(DataLocaliza[,2:10], na.rm=T)
                        )

  DataLocaliza_v2$Total <- sum(DataLocaliza_v2$Subtotal)

  DataLocaliza_v2 <- DataLocaliza_v2 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2))

return(DataLocaliza_v2)
}

# Aplicamos la función en cada localización:

Cabecera <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Cabecera Urbana")

VdaGuacamayal <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Guacamayal")

VdaVinia <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda La Viña")

VdaPalenque <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Palenque")

VdaPalenquito <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Palenquito")

VdaQuebAlta <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Quebradona Alta")

VdaQuebBaja <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Quebradona Baja")

VdaQuebMedia <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Quebradona Media")

CorrPaloCabil <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Corregimiento de Palocabildo")

VdaVallecitos <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Vallecitos")

VdaHermosa <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda La Hermosa")

VdaPista <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda La Pista")

VdaCabania <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda La Cabaña")

VdaBuga <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Buga")

VdaCauca <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda Cauca")

VdaLaFe <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Vereda La Fe")

CorrPuenteIg <- AgrupaInforma_v2(Data=Informacion,LocalizacionStr="Corregimiento de Puente Iglesias")

# Concatenamos la data:
Informacion_v2 <- join_all(list(Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebAlta,VdaQuebBaja,VdaQuebMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPuenteIg), by=c("Localizacion"),type = "full")

# Graficamos:
# Aunque este tipo de gráfico no es recomendabe por la cantidad de categorias:
ggplot(Informacion_v2, aes(x = Porcentaje, y = Localizacion, fill = Medio))+
  geom_bar(stat="identity",position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Producto Financiero:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4.4, vjust=0.4, hjust=-0.05 ,col="black")+
  theme(axis.title=element_text(size=rel(1.5)),
        axis.text.x=element_text(size=rel(1.5)),
        axis.text.y=element_text(size=rel(1.5)),
        legend.title=element_text(size=rel(1.3)),
        legend.text=element_text(size=rel(1)),
        legend.position="right"
        )+
  scale_x_continuous(limits=c(0,113))

# Paso opcional: exportamos data:
write_xlsx(Informacion_v2, "PdctoFinanciero.xlsx")

# Eliminamos intermedios:
rm(Informacion,Informacion_v2,AgrupaInforma_v2,Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebAlta,VdaQuebBaja,VdaQuebMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPuenteIg)
```

```{r Modulo Educación}
#### Tema: Condición educativa actual ####
# Pregunta de data: "${p_040}. ¿Cuál es su condición educativa actualmente?"
Educacion <- PilotoIndividuos %>%
  dplyr::select(.,"Localizacion","${p_040}. ¿Cuál es su condición educativa actualmente?") %>%
  dplyr::rename(CondicionEduca="${p_040}. ¿Cuál es su condición educativa actualmente?") %>% 
  dplyr::filter(.,CondicionEduca!="No responde",
                CondicionEduca!="No sabe",
                is.na(CondicionEduca)==F)

Educacion_v2 <- Agrupa(Data=Educacion,Columna=CondicionEduca)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=CondicionEduca))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Condición educativa:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,70))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "CondicionEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)

#### Tema: Causa para no continuar estudios ####
# Pregunta de data: "${p_040}. ¿Cuál fue la principal causa por la que no pudo continuar sus estudios?"

Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Cuál fue la principal causa por la que no pudo continuar sus estudios?") %>%
  dplyr::rename(CausaNoEstudio="${p_040}. ¿Cuál fue la principal causa por la que no pudo continuar sus estudios?") %>% 
  dplyr::filter(.,CausaNoEstudio!="No responde",
                CausaNoEstudio!="No sabe",
                is.na(CausaNoEstudio)==F) 

# Recodificamos categorias: 
Educacion$CausaCol <- c("Causa")

Educacion <- Educacion %>% 
  dplyr::mutate(CausaCol=ifelse(CausaNoEstudio=="Considera que ya terminó sus estudios","Ya terminó",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="No le gusta o no le interesa el estudio, aburrición","No le interesa",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Costos educativos elevados o falta de dinero","Costos educativos",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Necesita trabajar","Necesita trabajar",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="No existe centro educativo cercano, está muy lejano","Lejanía del centro educativo",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Por embarazo","Por embarazo",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Falta de tiempo","Falta de tiempo",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Recibe malos tratos en el colegio","Recibe malos tratos",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Considera que no está en edad escolar","No está en edad escolar",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Razones familiares","Razones familiares",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Por enfermedad o incapacidad médica","Enfermedad o incapacidad",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Porque se casó o formó pareja","Vida en pareja",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Debe encargarse de los oficios del hogar (cuidado de los niños, ancianos, personas con discapacidad, etc)","Oficios del hogar",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Necesita educación especial","Necesita educación especial",CausaCol),
                CausaCol=ifelse(CausaNoEstudio=="Por inseguridad en el establecimiento educativo, en el entorno del establecimiento o en el lugar de residencia","Inseguridad",CausaCol)  
                )

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=CausaCol)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=CausaCol))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Causa para no estudiar:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="right",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,70))

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "CausasEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)

#### Tema: Nivel de estudios que cursa actual ####
# Pregunta data: ${p_040}. ¿Cuál es el nivel actual de estudio?"
Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Cuál es el nivel actual de estudio?") %>%
  dplyr::rename(NivelEstudio="${p_040}. ¿Cuál es el nivel actual de estudio?") %>% 
  dplyr::filter(NivelEstudio!="No sabe",
                is.na(NivelEstudio)==F)

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=NivelEstudio)

# Data en factores con orden predeterminado
Educacion_v2$NivelEstudio <- factor(Educacion_v2$NivelEstudio, levels=c("Primaria (1º a 5º)","Secundaria (6º a 9º)", "Media (10º a 11º)","Técnico","Tecnológico","Universidad"))

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=NivelEstudio))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Nivel de estudio:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="right",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,90))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "NivelEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)

#### Tema: Area del conocimiento que cursa actualmente ####
# Pregunta de data: "${p_040}. Área de conocimiento de lo que está estudiando actualmente"
Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. Área de conocimiento de lo que está estudiando actualmente") %>%
  dplyr::rename(AreaEstudio="${p_040}. Área de conocimiento de lo que está estudiando actualmente") %>% 
  dplyr::filter(.,AreaEstudio!="No responde",
                is.na(AreaEstudio)==F)

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=AreaEstudio)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=AreaEstudio))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Area del conocimiento:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "AreaEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)

#### Tema: Ultimo título aprobado ####
# Pregunta data: "${p_040}. Último título de estudio aprobado."

Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. Último título de estudio aprobado.") %>%
  dplyr::rename(Titulo="${p_040}. Último título de estudio aprobado.")%>% 
  dplyr::filter(Titulo!="No responde",
                Titulo!="No sabe",
                is.na(Titulo)==F)

# Data en factores con orden predeterminado
Educacion$Titulo <- factor(Educacion$Titulo, levels=c("Ninguno","Prescolar","Primaria (1º a 5º)","Secundaria (6º a 9º)", "Media (10º a 11º)","Técnico","Tecnológico","Pregrado","Maestría"))

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=Titulo)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=Titulo))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Último título:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="right",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,75))

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "Tiitulo.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)


#### Tema: Area del conocimiento Ultimo título ####
# Pregunta de data: "${p_040}. Área de conocimiento en la que obtuvo el título."
Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. Área de conocimiento en la que obtuvo el título.") %>%
  dplyr::rename(AreaEstudio="${p_040}. Área de conocimiento en la que obtuvo el título.") %>% 
  dplyr::filter(.,AreaEstudio!="No responde",
                is.na(AreaEstudio)==F)

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=AreaEstudio)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=AreaEstudio))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Área del conocimiento del título:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "AreaEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)


#### Tema: Intereses académicos a futuro ####
# Pregunta data: "${p_040}. ¿Cuáles son sus intereses académicos a futuro? (¿Qué le gustaría aprender?)"

# Se debe mejorar el filtro en esta data
Educacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Cuáles son sus intereses académicos a futuro? (¿Qué le gustaría aprender?)") %>%
  dplyr::rename(InteresEstudiar="${p_040}. ¿Cuáles son sus intereses académicos a futuro? (¿Qué le gustaría aprender?)") %>% 
  dplyr::filter(.,is.na(InteresEstudiar)==F,
                InteresEstudiar!="No responde",
                InteresEstudiar!="No sabe",
                InteresEstudiar!="Retomar estudios en lo que estaba estudiando",
                InteresEstudiar!="Terminar estudios actuales (solo para quien estudia)",
                InteresEstudiar!="Retomar estudios diferente a lo que estaba estudiando",
                ) 

# Data en factores con orden predeterminado
Educacion$InteresEstudiar <- factor(Educacion$InteresEstudiar, levels=c("No tiene intereses académicos","Estudiar la primaria","Estudiar la secundaria","Estudiar la media","Estudiar una técnica","Estudiar una tecnología","Estudiar un pregrado","Estudiar un posgrado"))

Educacion_v2 <- Agrupa(Data=Educacion,
                 Columna=InteresEstudiar)

# Graficamos:
ggplot(Educacion_v2, aes(x=Porcentaje,y=Localizacion,fill=InteresEstudiar))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Interés académico:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="right",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,80))

# Paso opcional: exportamos data:
write_xlsx(Educacion_v2, "InteresEduca.xlsx")

# Eliminamos intermedios:
rm(Educacion,Educacion_v2)
```

```{r Modulo Seguridad Social}
#### Tema: Afiliación al SSS ####

#"${p_040}. Afiliación al Sistema de Seguridad Social en Salud."
AfiliacionSSS <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. Afiliación al Sistema de Seguridad Social en Salud.") %>%
  dplyr::rename(AfiliacionCol="${p_040}. Afiliación al Sistema de Seguridad Social en Salud.")  %>% 
  dplyr::filter(.,AfiliacionCol!="No responde",
                is.na(AfiliacionCol)==F)

Afiliacion_v2 <- Agrupa(Data=AfiliacionSSS,
                 Columna=AfiliacionCol)

# Graficamos:
ggplot(Afiliacion_v2, aes(x=Porcentaje,y=Localizacion,fill=AfiliacionCol))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Afiliación al sistema de salud:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,100))

# Paso opcional: exportamos data:
write_xlsx(Afiliacion_v2, "AfiliacionSalud.xlsx")

# Eliminamos intermedios:
rm(AfiliacionSSS,Afiliacion_v2)

#### Tema: Calificación: Servicios Salud  ####
# Pregunta data: "${p_040}. Según su opinión, ¿cómo califica la calidad de los servicios de salud?"

Salud <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. Según su opinión, ¿cómo califica la calidad de los servicios de salud?")) %>%
  dplyr::rename(Calificacion="${p_040}. Según su opinión, ¿cómo califica la calidad de los servicios de salud?") %>% 
  dplyr::filter(Calificacion!="No se encuentra en casa",
                Calificacion!="No responde",
                is.na(Calificacion)==F)

# Data en factores con orden predeterminado
Salud$Calificacion <- factor(Salud$Calificacion, levels=c("Malo","Regular","Bueno"))

Salud_v2 <- Agrupa(Data=Salud,
                 Columna=Calificacion)

# Graficamos:

ggplot(Salud_v2, aes(x=Porcentaje,y=Localizacion,fill=Calificacion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Calificación de servicios de salud:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,110))+
  scale_fill_brewer(palette=2)

# Paso opcional: exportamos data:
write_xlsx(Salud_v2, "CalificaSalud.xlsx")

# Eliminamos intermedios:
rm(Salud,Salud_v2)

#### Tema: Cotiza para pensión  ####
# Pregunta data: "${p_040}. ¿Cotiza para pensión?"

Salud <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Cotiza para pensión?")) %>%
  dplyr::rename(Cotiza="${p_040}. ¿Cotiza para pensión?") %>% 
  dplyr::filter(Cotiza!="No responde",
                Cotiza!="No sabe",
                is.na(Cotiza)==F)

Salud_v2 <- Agrupa(Data=Salud,
                 Columna=Cotiza)

# Graficamos:
ggplot(Salud_v2, aes(x=Porcentaje,y=Localizacion,fill=Cotiza))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Cotización al sistema de pensión:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.4),
            size=3.5, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,110))

# Paso opcional: exportamos data:
write_xlsx(Salud_v2, "CotizaPensión.xlsx")

# Eliminamos intermedios:
rm(Salud,Salud_v2)

#### Tema: Está afiliado a ARL  ####
# Pregunta data: "${p_040}. ¿Tiene Afiliación a una Administradora de Riesgos Laborales (ARL)?"

Salud <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Tiene Afiliación a una Administradora de Riesgos Laborales (ARL)?")) %>%
  dplyr::rename(Cotiza="${p_040}. ¿Tiene Afiliación a una Administradora de Riesgos Laborales (ARL)?") %>% 
  dplyr::filter(Cotiza!="No responde",
                Cotiza!="No sabe",
                is.na(Cotiza)==F)
          
Salud_v2 <- Agrupa(Data=Salud,
                 Columna=Cotiza)

# Graficamos:
ggplot(Salud_v2, aes(x=Porcentaje,y=Localizacion,fill=Cotiza))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Afiliación a ARL:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.4),
            size=3.5, vjust=0.5, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,110))

# Paso opcional: exportamos data:
write_xlsx(Salud_v2, "AfiliaciónARL.xlsx")

# Eliminamos intermedios:
rm(Salud,Salud_v2)
```

```{r Modulo Recreación}
#### Tema: Participación política ####
# Pregunta data: "${p_040}. ¿Usted participa en alguna de las siguientes organizaciones o instancias de participación?"

Recreacion <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Usted participa en alguna de las siguientes organizaciones o instancias de participación?") %>%
  dplyr::rename(RecreacionCol="${p_040}. ¿Usted participa en alguna de las siguientes organizaciones o instancias de participación?") %>%
  dplyr::filter(RecreacionCol!="No sabe",
                RecreacionCol!="Ninguno",
                RecreacionCol!="No responde",
                is.na(RecreacionCol)==F)

# Recodificamos categorias: 
Recreacion$RecreacionCol2 <- c("Recreación")

Recreacion <- Recreacion %>% 
  dplyr::mutate(RecreacionCol2=ifelse(RecreacionCol=="Juntas administradoras locales - JAL","Juntas administradoras locales",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Junta de acción comunal - JAC","Junta de acción comunal",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Veedurías ciudadanas","Veedurías ciudadanas",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Clubes del adulto mayor","Clubes del adulto mayor",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Asociaciones de mujeres","Asociaciones de mujeres",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="sindicatos","Sindicatos",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="COPACOS - Comités de participación comunitaria en salud","COPACOS",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Grupos juveniles","Grupos juveniles",RecreacionCol2),
                RecreacionCol2=ifelse(RecreacionCol=="Asociación de usuarios","Asociación de usuarios",RecreacionCol2)
                )


Recreacion_v2 <- Agrupa(Data=Recreacion,
                 Columna=RecreacionCol2)

# Graficamos:

ggplot(Recreacion_v2, aes(x=Porcentaje,y=Localizacion,fill=RecreacionCol2))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Instancias de participación:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Recreacion_v2, "Participación.xlsx")

# Eliminamos intermedios:
rm(Recreacion,Recreacion_v2)


#### Tema: Hobbies ####
# Preguntas data: 
# "${p_040}. ¿Cuáles son sus hobbies?/Bailar"
# "${p_040}. ¿Cuáles son sus hobbies?/Bricolaje"
# "${p_040}. ¿Cuáles son sus hobbies?/Cantar"
# "${p_040}. ¿Cuáles son sus hobbies?/Cocina"
# "${p_040}. ¿Cuáles son sus hobbies?/Contactar y conversar"
# "${p_040}. ¿Cuáles son sus hobbies?/Coser"
# "${p_040}. ¿Cuáles son sus hobbies?/Escribir"
# "${p_040}. ¿Cuáles son sus hobbies?/Escuchar música"
# "${p_040}. ¿Cuáles son sus hobbies?/Fotografía"
# "${p_040}. ¿Cuáles son sus hobbies?/Hacer deporte"
# "${p_040}. ¿Cuáles son sus hobbies?/Informarse"
# "${p_040}. ¿Cuáles son sus hobbies?/Jardinería"
# "${p_040}. ¿Cuáles son sus hobbies?/Juegos de mesa o azar"
# "${p_040}. ¿Cuáles son sus hobbies?/Leer"
# "${p_040}. ¿Cuáles son sus hobbies?/Manualidades"
# "${p_040}. ¿Cuáles son sus hobbies?/Meditación, yoga y relajación."
# "${p_040}. ¿Cuáles son sus hobbies?/Ocio electrónico"
# "${p_040}. ¿Cuáles son sus hobbies?/Pintar"
# "${p_040}. ¿Cuáles son sus hobbies?/Series o cine"
# "${p_040}. ¿Cuáles son sus hobbies?/Teatro"
# "${p_040}. ¿Cuáles son sus hobbies?/Tocar un instrumento"
# "${p_040}. ¿Cuáles son sus hobbies?/Viajar"
# "${p_040}. ¿Cuáles son sus hobbies?/Montar a caballo"
# "${p_040}. ¿Cuáles son sus hobbies?/Juegos infantiles"
# "${p_040}. ¿Cuáles son sus hobbies?/Reparación de motos"

Hobbies <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Cuáles son sus hobbies?/Bailar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Bricolaje",
                    "${p_040}. ¿Cuáles son sus hobbies?/Cantar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Cocina",
                    "${p_040}. ¿Cuáles son sus hobbies?/Contactar y conversar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Coser",
                    "${p_040}. ¿Cuáles son sus hobbies?/Escribir",
                    "${p_040}. ¿Cuáles son sus hobbies?/Escuchar música",
                    "${p_040}. ¿Cuáles son sus hobbies?/Fotografía",
                    "${p_040}. ¿Cuáles son sus hobbies?/Hacer deporte",
                    "${p_040}. ¿Cuáles son sus hobbies?/Informarse",
                    "${p_040}. ¿Cuáles son sus hobbies?/Jardinería",
                    "${p_040}. ¿Cuáles son sus hobbies?/Juegos de mesa o azar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Leer",
                    "${p_040}. ¿Cuáles son sus hobbies?/Manualidades",
                    "${p_040}. ¿Cuáles son sus hobbies?/Meditación, yoga y relajación.",
                    "${p_040}. ¿Cuáles son sus hobbies?/Ocio electrónico",
                    "${p_040}. ¿Cuáles son sus hobbies?/Pintar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Series o cine",
                    "${p_040}. ¿Cuáles son sus hobbies?/Teatro",
                    "${p_040}. ¿Cuáles son sus hobbies?/Tocar un instrumento",
                    "${p_040}. ¿Cuáles son sus hobbies?/Viajar",
                    "${p_040}. ¿Cuáles son sus hobbies?/Montar a caballo",
                    "${p_040}. ¿Cuáles son sus hobbies?/Juegos infantiles",
                    "${p_040}. ¿Cuáles son sus hobbies?/Reparación de motos"
                    )
                ) %>%
  dplyr::rename(Bailar="${p_040}. ¿Cuáles son sus hobbies?/Bailar",
                Bricolaje="${p_040}. ¿Cuáles son sus hobbies?/Bricolaje",
                Cantar="${p_040}. ¿Cuáles son sus hobbies?/Cantar",
                Cocina="${p_040}. ¿Cuáles son sus hobbies?/Cocina",
                Conversar="${p_040}. ¿Cuáles son sus hobbies?/Contactar y conversar",
                Coser="${p_040}. ¿Cuáles son sus hobbies?/Coser",
                Escribir="${p_040}. ¿Cuáles son sus hobbies?/Escribir",
                "Escuchar Musica"="${p_040}. ¿Cuáles son sus hobbies?/Escuchar música",
                Fotografía="${p_040}. ¿Cuáles son sus hobbies?/Fotografía",
                "Practicar deporte"="${p_040}. ¿Cuáles son sus hobbies?/Hacer deporte",
                Informarse="${p_040}. ¿Cuáles son sus hobbies?/Informarse",
                Jardinería="${p_040}. ¿Cuáles son sus hobbies?/Jardinería",
                "Juegos de azar"="${p_040}. ¿Cuáles son sus hobbies?/Juegos de mesa o azar",
                Leer="${p_040}. ¿Cuáles son sus hobbies?/Leer",
                Manualidades="${p_040}. ¿Cuáles son sus hobbies?/Manualidades",
                Meditacion="${p_040}. ¿Cuáles son sus hobbies?/Meditación, yoga y relajación.",
                "Ocio virtual"="${p_040}. ¿Cuáles son sus hobbies?/Ocio electrónico",
                Pintar="${p_040}. ¿Cuáles son sus hobbies?/Pintar",
                Series="${p_040}. ¿Cuáles son sus hobbies?/Series o cine",
                Teatro="${p_040}. ¿Cuáles son sus hobbies?/Teatro",
                "Tocar instrumento"="${p_040}. ¿Cuáles son sus hobbies?/Tocar un instrumento",
                Viajar="${p_040}. ¿Cuáles son sus hobbies?/Viajar",
                "Montar caballo"="${p_040}. ¿Cuáles son sus hobbies?/Montar a caballo",
                "Juegos infantiles"="${p_040}. ¿Cuáles son sus hobbies?/Juegos infantiles",
                "Reparación de motos"="${p_040}. ¿Cuáles son sus hobbies?/Reparación de motos"
                )

# Volvemos todas las columnas en tipo numéricas:
Hobbies$Bailar <- as.numeric(Hobbies$Bailar)
Hobbies$Bricolaje <- as.numeric(Hobbies$Bricolaje)
Hobbies$Cantar <- as.numeric(Hobbies$Cantar)
Hobbies$Cocina <- as.numeric(Hobbies$Cocina)
Hobbies$Conversar <- as.numeric(Hobbies$Conversar)
Hobbies$Coser <- as.numeric(Hobbies$Coser)
Hobbies$Escribir <- as.numeric(Hobbies$Escribir)
Hobbies$`Escuchar Musica`<- as.numeric(Hobbies$`Escuchar Musica`)
Hobbies$Fotografía <- as.numeric(Hobbies$Fotografía)
Hobbies$`Practicar deporte` <- as.numeric(Hobbies$`Practicar deporte`)
Hobbies$Informarse <- as.numeric(Hobbies$Informarse)
Hobbies$Jardinería <- as.numeric(Hobbies$Jardinería)
Hobbies$`Juegos de azar` <- as.numeric(Hobbies$`Juegos de azar`)
Hobbies$Leer <- as.numeric(Hobbies$Leer)
Hobbies$Manualidades <- as.numeric(Hobbies$Manualidades)
Hobbies$Meditacion <- as.numeric(Hobbies$Meditacion)
Hobbies$`Ocio virtual` <- as.numeric(Hobbies$`Ocio virtual`)
Hobbies$Pintar <- as.numeric(Hobbies$Pintar)
Hobbies$Series <- as.numeric(Hobbies$Series)
Hobbies$Teatro <- as.numeric(Hobbies$Teatro)
Hobbies$`Tocar instrumento` <- as.numeric(Hobbies$`Tocar instrumento`)
Hobbies$Viajar <- as.numeric(Hobbies$Viajar)
Hobbies$`Montar caballo` <- as.numeric(Hobbies$`Montar caballo`)
Hobbies$`Juegos infantiles` <- as.numeric(Hobbies$`Juegos infantiles`)
Hobbies$`Reparación de motos` <- as.numeric(Hobbies$`Reparación de motos`)


# vamos a crear subgrupos por localidad y luego se concatenan. Para esto creamos una función:
# Funcion:
# Esta función usa la data inicial y la localización que queremos usar:
AgrupaInforma <- function(Data,LocalizacionStr){
  
  DataLocaliza <- Data %>% 
  dplyr::filter(Localizacion==LocalizacionStr)

  DataLocaliza_v2 <- data.frame("Localizacion"=c(LocalizacionStr),
                      "Hobbie"=c("Bailar","Bricolaje","Cantar","Cocina","Conversar","Coser","Escribir","Escuchar Musica","Fotografía","Practicar deporte","Informarse","Jardinería","Juegos de azar","Leer","Manualidades","Meditacion","Ocio virtual","Pintar","Series","Teatro","Tocar instrumento","Viajar","Montar caballo","Juegos infantiles","Reparación de motos"),
                      "Subtotal"=colSums(DataLocaliza[,2:26], na.rm=T)
                        )

  DataLocaliza_v2$Total <- sum(DataLocaliza_v2$Subtotal)

  DataLocaliza_v2 <- DataLocaliza_v2 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2))

return(DataLocaliza_v2)
}

# Aplicamos la función en cada localización:
Cabecera <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Cabecera Urbana")
VdaGuacamayal <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Guacamayal")
VdaVinia <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda La Viña")
VdaPalenque <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Palenque")
VdaPalenquito <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Palenquito")
VdaQuebraAlta <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Quebradona Alta")
VdaQuebraBaja <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Quebradona Baja")
VdaQuebraMedia <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Quebradona Media")
CorrPaloCabil <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Corregimiento de Palocabildo")
VdaVallecitos <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Vallecitos")
VdaHermosa <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda La Hermosa")
VdaPista <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda La Pista")
VdaCabania <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda La Cabaña")
VdaBuga <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Buga")
VdaCauca <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda Cauca")
VdaLaFe <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Vereda La Fe")
CorrPteIgle <- AgrupaInforma(Data=Hobbies,LocalizacionStr="Corregimiento de Puente Iglesias")

# Concatenamos la data:
Hobbies_v2 <- join_all(list(Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebraAlta,VdaQuebraBaja,VdaQuebraMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPteIgle), by=c("Localizacion"),type = "full")

Hobbies_v2 <- Hobbies_v2 %>% 
  dplyr::filter(Porcentaje!=0.00)

# Graficamos:
# Aunque este tipo de gráfico no es recomendabe por la cantidad de categorias:
ggplot(Hobbies_v2, aes(x = Porcentaje, y = Localizacion, fill = Hobbie))+
  geom_bar(stat="identity",position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Hobbie:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3, vjust=0.4, hjust=-0.05 ,col="black")+
  theme(axis.title=element_text(size=rel(1.5)),
        axis.text.x=element_text(size=rel(1.5)),
        axis.text.y=element_text(size=rel(1.5)),
        legend.title=element_text(size=rel(1.3)),
        legend.text=element_text(size=rel(1)),
        legend.position="right",
        legend.direction = "vertical"
        )+
  scale_x_continuous(limits=c(0,45))

# Paso opcional: exportamos data:
write_xlsx(Hobbies_v2, "Hobbies.xlsx")

# Eliminamos intermedios:
rm(Hobbies,Hobbies_v2,Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebraAlta,VdaQuebraBaja,VdaQuebraMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPteIgle,AgrupaInforma)
```

```{r Modulo Movilidad}
#### Tema: Medio de transporte al centro educativo ####
# Pregunta data: "${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro educativo?"

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro educativo?") %>%
  dplyr::rename(MovilEduca="${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro educativo?") %>%
  dplyr::filter(is.na(MovilEduca)==F) 

Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=MovilEduca)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=MovilEduca))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Medio de transporte al centro educativo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "MovilEduca.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)

#### Tema: Medio de transporte a Recreación ####
# Pregunta data: ${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro de recreación (para realizar hobbies)?

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro de recreación (para realizar hobbies)?") %>%
  dplyr::rename(Movil="${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse a su centro de recreación (para realizar hobbies)?")%>%
  dplyr::filter(Movil!="No responde",
                Movil!="No sabe",
                is.na(Movil)==F)

Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=Movil)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=Movil))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Medio de transporte al centro recreativo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "MovilRecrea.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)

#### Tema: Medio de transporte al trabajo ####
# Pregunta data: "${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse al sitio de su empleo principal?"

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse al sitio de su empleo principal?") %>%
  dplyr::rename(Movil="${p_040}. ¿Qué medio de transporte utiliza predominantemente para dirigirse al sitio de su empleo principal?")%>%
  dplyr::filter(Movil!="No responde",
                Movil!="No sabe",
                is.na(Movil)==F)

Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=Movil)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=Movil))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Medio de transporte al sitio laboral:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "MovilTrabajo.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)

#### Tema: Tiempo en transportarse ####
# Pregunta data: "${p_040}. ¿Cuánto tiempo tarda en llegar a su centro educativo? (minutos)"
# Pregunta data: "${p_040}. ¿Cuánto tiempo tarda en llegar a su centro de recreación (para realizar hobbies)? (minutos)"
# Pregunta data: "${p_040}. ¿Cuánto tiempo tarda en llegar al sitio de su empleo principal? (minutos)"

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Cuánto tiempo tarda en llegar a su centro educativo? (minutos)","${p_040}. ¿Cuánto tiempo tarda en llegar a su centro de recreación (para realizar hobbies)? (minutos)","${p_040}. ¿Cuánto tiempo tarda en llegar al sitio de su empleo principal? (minutos)")) %>%
  dplyr::rename(MovilEduca="${p_040}. ¿Cuánto tiempo tarda en llegar a su centro educativo? (minutos)",MovilRecrea="${p_040}. ¿Cuánto tiempo tarda en llegar a su centro de recreación (para realizar hobbies)? (minutos)",MovilTrabajo="${p_040}. ¿Cuánto tiempo tarda en llegar al sitio de su empleo principal? (minutos)") 

# Transformamos data a tipo numérico
Movilidad$MovilEduca <- as.numeric(Movilidad$MovilEduca)
Movilidad$MovilRecrea <- as.numeric(Movilidad$MovilRecrea)
Movilidad$MovilTrabajo <- as.numeric(Movilidad$MovilTrabajo)

# Creamos DFs: con promedios de tiempo por localización:

TiempoEduca <- Movilidad %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      Tiempo = round(mean(MovilEduca,na.rm = TRUE),2)
      )

TiempoEduca$Destino <- c("Centro educativo")

TiempoRecrea <- Movilidad %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      Tiempo = round(mean(MovilRecrea,na.rm = TRUE),2)
      )

TiempoRecrea$Destino <- c("Centro recreativo")

TiempoLabora <- Movilidad %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      Tiempo = round(mean(MovilTrabajo,na.rm = TRUE),2)
      )

TiempoLabora$Destino <- c("Sitio laboral")

# Concatenamos la data:
Tiempos <- join_all(list(TiempoEduca,TiempoRecrea,TiempoLabora), by=c("Destino"),type = "full")

Tiempos <- Tiempos %>% 
  dplyr::filter(is.na(Tiempo)==F)


# Graficamos:
ggplot(Tiempos, aes(x=Tiempo,y=Localizacion,fill=Destino))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Tiempo promedio",y="Localización",fill="Destino:")+
  geom_text(aes(label = Tiempo),position = position_dodge(1),
            size=3.4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,100))

# Paso opcional: exportamos data:
write_xlsx(Tiempos, "TiemposMovilidad.xlsx")

# Eliminamos intermedios:
rm(Movilidad,TiempoEduca,TiempoRecrea,TiempoLabora,Tiempos)

#### Tema: Calificación vías: Educación  ####
# Pregunta data: "${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro educativo?"

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro educativo?")) %>%
  dplyr::rename(MovilEduca="${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro educativo?") %>%
  dplyr::filter(MovilEduca!="No se encuentra en casa",
                is.na(MovilEduca)==F)

# Data en factores con orden predeterminado
Movilidad$MovilEduca <- factor(Movilidad$MovilEduca, levels=c("Malo","Regular","Bueno"))


Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=MovilEduca)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=MovilEduca))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Calificación vías al centro educativo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "CalifiMovilEduca.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)


#### Tema: Calificación vías: Recreación ####
# Pregunta data: "${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro de recreación"
Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro de recreación (para realizar hobbies)?")) %>%
  dplyr::rename(MovilRecrea="${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse a su centro de recreación (para realizar hobbies)?") %>%
  dplyr::filter(MovilRecrea!="No responde",
                MovilRecrea!="No se encuentra en casa",
                is.na(MovilRecrea)==F)

# Data en factores con orden predeterminado
Movilidad$MovilRecrea <- factor(Movilidad$MovilRecrea, levels=c("Malo","Regular","Bueno"))

Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=MovilRecrea)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=MovilRecrea))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Calificación vías al centro recreativo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "CalifiMovilRecrea.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)

#### Tema: Calificación vías: Trabajo ####
# Pregunta data: "${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse al sitio de su empleo principal?"

Movilidad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse al sitio de su empleo principal?")) %>%
  dplyr::rename(MovilTrabajo="${p_040}. En su opinión: ¿cuál es el estado de las vías que utiliza para dirigirse al sitio de su empleo principal?") %>%  dplyr::filter(MovilTrabajo!="No se encuentra en casa",
                is.na(MovilTrabajo)==F)

# Data en factores con orden predeterminado
Movilidad$MovilTrabajo <- factor(Movilidad$MovilTrabajo, levels=c("Malo","Regular","Bueno"))

Movilidad_v2 <- Agrupa(Data=Movilidad,
                 Columna=MovilTrabajo)

# Graficamos:

ggplot(Movilidad_v2, aes(x=Porcentaje,y=Localizacion,fill=MovilTrabajo))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Calificación vías al sitio laboral:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Movilidad_v2, "CalifiMovilLaboral.xlsx")

# Eliminamos intermedios:
rm(Movilidad,Movilidad_v2)
```

```{r Modulo Laboral e ingresos}
#### Tema: Actividad semana pasada ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,Localizacion,"${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]") %>%
  dplyr::rename(ActividadCol="${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]") %>%  dplyr::filter(ActividadCol!="No responde",
                is.na(ActividadCol)==F) 

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=ActividadCol)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=ActividadCol))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Actividad última semana:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "Actividad.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Localización empleo ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. ¿Municipio donde está ubicado su empleo principal?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Municipio donde está ubicado su empleo principal?")) %>%
  dplyr::rename(LocalizaTrabajo="${p_040}. ¿Municipio donde está ubicado su empleo principal?") %>% 
  dplyr::filter(is.na(LocalizaTrabajo)==F) 

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=LocalizaTrabajo)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=LocalizaTrabajo))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Localización del empleo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "LocalizaEmpleo.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Sector económico empresa ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. ¿A qué actividad específica se dedica principalmente la empresa o negocio en la que realiza su trabajo?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿A qué actividad específica se dedica principalmente la empresa o negocio en la que realiza su trabajo?")) %>%
  dplyr::rename(Sector="${p_040}. ¿A qué actividad específica se dedica principalmente la empresa o negocio en la que realiza su trabajo?") %>% 
  dplyr::filter(is.na(Sector)==F,
                Sector!="No responde") 

# Recodificamos variables:
Actividad$SectorShort <- c("Sector")

Actividad <- Actividad %>% 
  dplyr::mutate(SectorShort=ifelse(Sector=="A-Agricultura, Ganadería, Caza, Silvicultura y Pesca","A-Agricultura",SectorShort),
                SectorShort=ifelse(Sector=="C-Industrias manufactureras","C-Industrias manufactureras",SectorShort),
                SectorShort=ifelse(Sector=="H-Transporte y almacenamiento","H-Transporte y almacenamiento",SectorShort),
                SectorShort=ifelse(Sector=="G-Comercio al por mayor y por menor; reparación de vehículos y motos","G-Comercio",SectorShort),
                SectorShort=ifelse(Sector=="T-Actividades de hogares individuales.","T-Actividades de hogares",SectorShort),
                SectorShort=ifelse(Sector=="F-Construcción","F-Construcción",SectorShort),
                SectorShort=ifelse(Sector=="P-Educación","P-Educación",SectorShort),
                SectorShort=ifelse(Sector=="Q-Actividades de atención de la salud humana y asistencia social","Q-Salud humana y asistencia social",SectorShort),
                SectorShort=ifelse(Sector=="S-Otras actividades de servicios","S-Otros servicios",SectorShort),
                SectorShort=ifelse(Sector=="J-Información y comunicaciones","J-Información y comunicaciones",SectorShort),
                SectorShort=ifelse(Sector=="N-Actividades de servicio administrativo y de apoyo","N-Actividades administrativas y de apoyo",SectorShort),
                SectorShort=ifelse(Sector=="I-Alojamiento y servicios de comida","I-Alojamiento y comida",SectorShort),
                SectorShort=ifelse(Sector=="R-Actividades Artisticas, de entretenimiento y recreación.","R-Actividades Artisticas y recreación",SectorShort),
                SectorShort=ifelse(Sector=="K-Actividades financieras y de seguros","K-Actividades financieras",SectorShort),
                SectorShort=ifelse(Sector=="B-Explotación de Minas y canteras","B-Explotación de Minas",SectorShort),
                SectorShort=ifelse(Sector=="M-Actividades profesionales, científicas y técnicas","M-Actividades profesionales",SectorShort),
                SectorShort=ifelse(Sector=="D-Suministro de electricidad, gas, vapor y aire acondicionado","D-Suministro de electricidad",SectorShort),
                SectorShort=ifelse(Sector=="E-Distribución de agua, evacuación y tratamiento de residuos; gestión de desechos y saneamiento","E-Distribución de agua",SectorShort),
                SectorShort=ifelse(Sector=="O-Administración pública y defensa","O-Administración pública",SectorShort),
                )
# Agrupamos como corresponde:
Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=SectorShort)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=SectorShort))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Sector económico del empleo:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "SectorEmpleo.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)


#### Tema: Posición ocupacional ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. En este trabajo es:"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. En este trabajo es:")) %>%
  dplyr::rename(Posicion="${p_040}. En este trabajo es:")%>% 
  dplyr::filter(Posicion!="No sabe",
                is.na(Posicion)==F)  

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Posicion)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Posicion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Posición ocupacional:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,90))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "PosicionOcupacional.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Horas en su empleo ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. ¿Cuántas horas a la semana trabaja normalmente en ese trabajo principal?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Cuántas horas a la semana trabaja normalmente en ese trabajo principal?")) %>%
  dplyr::rename(Horas="${p_040}. ¿Cuántas horas a la semana trabaja normalmente en ese trabajo principal?")%>% 
  dplyr::filter(is.na(Horas)==F,
                Horas>0) # eliminamos valores negativos

# Transformamos data a tipo numérico
Actividad$Horas <- as.numeric(Actividad$Horas)

# Creamos DF: con promedios de tiempo por localización:

Tiempos <- Actividad %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      Tiempo = round(mean(Horas,na.rm = TRUE),2)
      )

# Graficamos:
ggplot(Tiempos, aes(x=Tiempo,y=Localizacion))+
  geom_bar(stat="identity", position="dodge",fill="cyan4")+
  labs(x="Horas (promedio) por semana",y="Localización")+
  geom_text(aes(label = Tiempo),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,55))+
  scale_fill_brewer(palette=1)

# Paso opcional: exportamos data:
write_xlsx(Tiempos, "HorasTrabajo.xlsx")

# Eliminamos intermedios:
rm(Actividad,Tiempos)

#### Tema: Tiene Contrato ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. ¿Para realizar este trabajo tiene algún contrato?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Para realizar este trabajo tiene algún contrato?")) %>%
  dplyr::rename(Contrato="${p_040}. ¿Para realizar este trabajo tiene algún contrato?")%>% 
  dplyr::filter(Contrato!="No responde",
                Contrato!="No sabe",
                is.na(Contrato)==F)  

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Contrato)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Contrato))+
  geom_col()+
  labs(x="Porcentaje",y="Localización",fill="Tiene contrato laboral:")+
  geom_text(aes(label = Porcentaje),position = position_stack(0.4),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,110), breaks=c(0,50,100))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "Contrato.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Duración Contrato ####
# Pregunta data: "${p_040}. ¿En qué actividad ocupó la mayor parte del tiempo la semana pasada? [la predominante]"
# Pregunta data: "${p_040}. ¿Para realizar este trabajo tiene algún contrato?"
# Pregunta data: "${p_040}. ¿Qué término tiene el contrato?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Qué término tiene el contrato?")) %>%
  dplyr::rename(Duracion="${p_040}. ¿Qué término tiene el contrato?")%>% 
  dplyr::filter(is.na(Duracion)==F)   

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Duracion)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Duracion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Duración contrato laboral:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "DuracionContrato.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)


#### Tema: Ingresos laborales ####
# Pregunta data: "${p_040}. ¿Cuánto ganó el mes pasado en este empleo? o ¿Cuánto recibio el mes pasado por concepto de trabajo?"
# Atención a esta variable: es suceptible a errores de tipeo

Actividad <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,"${p_040}. ¿Cuánto ganó el mes pasado en este empleo? o ¿Cuánto recibio el mes pasado por concepto de trabajo?")) %>%
  dplyr::rename(Ingresos="${p_040}. ¿Cuánto ganó el mes pasado en este empleo? o ¿Cuánto recibio el mes pasado por concepto de trabajo?")%>% 
  dplyr::filter(is.na(Ingresos)==F,
                Ingresos>0) # eliminamos valores negativos 

# Transformamos data a tipo numérico
Actividad$Ingresos <- as.numeric(Actividad$Ingresos)

# Creamos DF: con promedios de ingresos por localización:

Ingresos <- Actividad %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      "ingreso salarial" = round(mean(Ingresos,na.rm = TRUE),0)
      )

# Graficamos:
ggplot(Ingresos, aes(x=`ingreso salarial`,y=Localizacion))+
  geom_bar(stat="identity", position="dodge",fill="cyan4")+
  labs(x="Ingreso laboral (promedio) ",y="Localización")+
  geom_text(aes(label = `ingreso salarial`),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_fill_brewer(palette=1)+
  scale_x_continuous(limits=c(0,1300000))


# Paso opcional: exportamos data:
write_xlsx(Ingresos, "IngresoLaboral.xlsx")

# Eliminamos intermedios:
rm(Actividad,Ingresos)

#### Tema: Cuantia de Otros ingresos ####
# Atención a estas variables: suceptibles a errores de tipeo
# Preguntas data: 
# "${p_040}. ¿Cuánto recibió el mes pasado por concepto de ARRIENDOS?"
# "${p_040}. ¿Cuánto recibió el mes pasado por concepto de PENSIONES O JUBILACIONES?"
# "${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Giros de personas del exterior?"
# "${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Intereses o dividendos?"
# "${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Subsidios del estado?"

Ingresos <- PilotoIndividuos %>%
  dplyr::select(Localizacion,"${p_040}. ¿Cuánto recibió el mes pasado por concepto de ARRIENDOS?","${p_040}. ¿Cuánto recibió el mes pasado por concepto de PENSIONES O JUBILACIONES?","${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Giros de personas del exterior?","${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Intereses o dividendos?","${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Subsidios del estado?") %>%
  dplyr::rename("Arriendos (mes)"="${p_040}. ¿Cuánto recibió el mes pasado por concepto de ARRIENDOS?","Pensiones (mes)"="${p_040}. ¿Cuánto recibió el mes pasado por concepto de PENSIONES O JUBILACIONES?","Giros Exterior (anual)"="${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Giros de personas del exterior?", "Intereses (anual)"="${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Intereses o dividendos?","Subsidios (anual)"="${p_040}. ¿Cuánto EN TOTAL recibió durante los últimos 12 meses por Subsidios del estado?") 

# Transformamos data a tipo numérico
Ingresos$`Arriendos (mes)` <- as.numeric(Ingresos$`Arriendos (mes)`)
Ingresos$`Pensiones (mes)` <- as.numeric(Ingresos$`Pensiones (mes)`)
Ingresos$`Giros Exterior (anual)` <- as.numeric(Ingresos$`Giros Exterior (anual)`)
Ingresos$`Intereses (anual)` <- as.numeric(Ingresos$`Intereses (anual)`)
Ingresos$`Subsidios (anual)` <- as.numeric(Ingresos$`Subsidios (anual)`)


# Creamos DFs: con promedios de tiempo por localización:
# Creamos una función para simplifcar el proceso:
# La variable es el tipo de ingresos, y VariableStr es como quiero llamar esos ingresos

TipoIngresos <- function(Variable,VariableStr){
  Data <- Ingresos %>% 
    dplyr::filter({{Variable}}>0,
                  is.na({{Variable}})==F) %>%
    dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      "Promedio Ingreso" = round(mean({{Variable}},na.rm = TRUE),0)
      )
  Data$`Tipo Ingreso` <- c(VariableStr)

  return(Data)
}

Arriendos <- TipoIngresos(Variable=`Arriendos (mes)`,
                               VariableStr="Arriendos (mes)")

Pensiones <- TipoIngresos(Variable=`Pensiones (mes)`,
                               VariableStr="Pensión (mes)")

Giros <- TipoIngresos(Variable=`Giros Exterior (anual)`,
                      VariableStr="Giros Exterior (anual)")

Intereses <- TipoIngresos(Variable=`Intereses (anual)`,
                      VariableStr="Intereses (anual)")

Subsidios <- TipoIngresos(Variable=`Subsidios (anual)`,
                      VariableStr="Subsidios (anual)")

# Concatenamos la data:
Ingresos_v2 <- join_all(list(Arriendos,Pensiones,Giros,Intereses,Subsidios), by=c("Tipo Ingreso"),type = "full")

# Graficamos:
ggplot(Ingresos_v2, aes(x=`Promedio Ingreso`,y=Localizacion,fill=`Tipo Ingreso`))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Tiempo promedio",y="Localización",fill="Tipo de ingresos:")+
  geom_text(aes(label = `Promedio Ingreso`),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_fill_brewer(palette=1)#+
  #scale_x_continuous(limits=c(0,100))


# Paso opcional: exportamos data:
write_xlsx(Ingresos_v2, "OtrosIngresos.xlsx")

# Eliminamos intermedios:
rm(Ingresos,TipoIngresos,Arriendos,Pensiones,Giros,Intereses,Subsidios,Ingresos_v2)



#### Tema: Intereses laborales a futuro ####
# Pregunta data: "${p_040}. ¿Cuáles son sus intereses laborales a futuro? (¿Qué le gustaría hacer?)"

Actividad <- PilotoIndividuos %>%
  dplyr::select(Localizacion,"${p_040}. ¿Cuáles son sus intereses laborales a futuro? (¿Qué le gustaría hacer?)") %>%
  dplyr::rename(InteresLaboral="${p_040}. ¿Cuáles son sus intereses laborales a futuro? (¿Qué le gustaría hacer?)")%>% 
  dplyr::filter(is.na(InteresLaboral)==F,
                InteresLaboral!="No responde",
                InteresLaboral!="No sabe",
                InteresLaboral!="Otro")

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=InteresLaboral)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=InteresLaboral))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Intereses laborales a futuro:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,90))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "InteresLaboral.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Prioridad de inversión ####
# Pregunta data: "${p_040}. En su opinión: ¿cuál debería ser la prioridad de inversión en el municipio?"

Actividad <- PilotoIndividuos %>%
  dplyr::select(Localizacion,"${p_040}. En su opinión: ¿cuál debería ser la prioridad de inversión en el municipio?") %>%
  dplyr::rename(Inversion="${p_040}. En su opinión: ¿cuál debería ser la prioridad de inversión en el municipio?") %>% 
  dplyr::filter(Inversion!="No responde",
                Inversion!="No sabe",
                Inversion!="No se encuentra en casa",
                Inversion!="Otro",
                is.na(Inversion)==F)

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Inversion)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Inversion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Prioridad de inversión:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=3.5, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,60))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "PrioridadInversion.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)
#### Tema: Oficios ####
# Preguntas data: 
# "${p_040}. En general, ¿qué oficio sabe hacer?/...

Oficio <- PilotoIndividuos %>%
  dplyr::select(.,c(Localizacion,
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Agricultor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Albañil",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Animador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Artesano",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Barbero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Barrendero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Cajero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Carnicero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Carpintero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Cerrajero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Chofer o conductor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Cocinero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/deshollinador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Editor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Escritor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Escultor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Exterminador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Fontanero o plomero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Impresor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Lavandero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Lechero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Leñador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Locutor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Mecánico",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Obrero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Panadero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Pastor ganadero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Peletero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Peluquero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Pescador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Pintor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Policía",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Repartidor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Sastre",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Soldador",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Tornero",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Vendedor",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Vigilante",
                    "${p_040}. En general, ¿qué oficio sabe hacer?/Manualidades"
                    )) %>%
  dplyr::rename(Agricultor="${p_040}. En general, ¿qué oficio sabe hacer?/Agricultor",
                "Albañil"="${p_040}. En general, ¿qué oficio sabe hacer?/Albañil",
                Animador="${p_040}. En general, ¿qué oficio sabe hacer?/Animador",
                Artesano="${p_040}. En general, ¿qué oficio sabe hacer?/Artesano",
                Barbero="${p_040}. En general, ¿qué oficio sabe hacer?/Barbero",
                Barrendero="${p_040}. En general, ¿qué oficio sabe hacer?/Barrendero",
                Cajero="${p_040}. En general, ¿qué oficio sabe hacer?/Cajero",
                Carnicero="${p_040}. En general, ¿qué oficio sabe hacer?/Carnicero",
                Carpintero="${p_040}. En general, ¿qué oficio sabe hacer?/Carpintero",
                Cerrajero="${p_040}. En general, ¿qué oficio sabe hacer?/Cerrajero",
                Conductor="${p_040}. En general, ¿qué oficio sabe hacer?/Chofer o conductor",
                Cocinero="${p_040}. En general, ¿qué oficio sabe hacer?/Cocinero",
                Deshollinador="${p_040}. En general, ¿qué oficio sabe hacer?/deshollinador",
                Editor="${p_040}. En general, ¿qué oficio sabe hacer?/Editor",
                Escritor="${p_040}. En general, ¿qué oficio sabe hacer?/Escritor",
                Escultor="${p_040}. En general, ¿qué oficio sabe hacer?/Escultor",
                Exterminador="${p_040}. En general, ¿qué oficio sabe hacer?/Exterminador",
                Plomero="${p_040}. En general, ¿qué oficio sabe hacer?/Fontanero o plomero",
                Impresor="${p_040}. En general, ¿qué oficio sabe hacer?/Impresor",
                Lavandero="${p_040}. En general, ¿qué oficio sabe hacer?/Lavandero",
                Lechero="${p_040}. En general, ¿qué oficio sabe hacer?/Lechero",
                "Leñador"="${p_040}. En general, ¿qué oficio sabe hacer?/Leñador",
                Locutor="${p_040}. En general, ¿qué oficio sabe hacer?/Locutor",
                Mecanico="${p_040}. En general, ¿qué oficio sabe hacer?/Mecánico",
                Obrero="${p_040}. En general, ¿qué oficio sabe hacer?/Obrero",
                Panadero="${p_040}. En general, ¿qué oficio sabe hacer?/Panadero",
                "Pastor ganadero"="${p_040}. En general, ¿qué oficio sabe hacer?/Pastor ganadero",
                Peletero="${p_040}. En general, ¿qué oficio sabe hacer?/Peletero",
                Peluquero="${p_040}. En general, ¿qué oficio sabe hacer?/Peluquero",
                Pescador="${p_040}. En general, ¿qué oficio sabe hacer?/Pescador",
                Pintor="${p_040}. En general, ¿qué oficio sabe hacer?/Pintor",
                Policia="${p_040}. En general, ¿qué oficio sabe hacer?/Policía",
                Repartidor="${p_040}. En general, ¿qué oficio sabe hacer?/Repartidor",
                Sastre="${p_040}. En general, ¿qué oficio sabe hacer?/Sastre",
                Soldador="${p_040}. En general, ¿qué oficio sabe hacer?/Soldador",
                Tornero="${p_040}. En general, ¿qué oficio sabe hacer?/Tornero",
                Vendedor="${p_040}. En general, ¿qué oficio sabe hacer?/Vendedor",
                Vigilante="${p_040}. En general, ¿qué oficio sabe hacer?/Vigilante",
                Manualidades="${p_040}. En general, ¿qué oficio sabe hacer?/Manualidades"
                )

# Volvemos todas las columnaas en tipo numéricas:
Oficio$Agricultor <- as.numeric(Oficio$Agricultor)
Oficio$Albañil <- as.numeric(Oficio$Albañil)
Oficio$Animador <- as.numeric(Oficio$Animador)
Oficio$Artesano <- as.numeric(Oficio$Artesano)
Oficio$Barbero <- as.numeric(Oficio$Barbero)
Oficio$Barrendero <- as.numeric(Oficio$Barrendero)
Oficio$Cajero <- as.numeric(Oficio$Cajero)
Oficio$Carnicero <- as.numeric(Oficio$Carnicero)
Oficio$Carpintero <- as.numeric(Oficio$Carpintero)
Oficio$Cerrajero <- as.numeric(Oficio$Cerrajero)
Oficio$Conductor <- as.numeric(Oficio$Conductor)
Oficio$Cocinero <- as.numeric(Oficio$Cocinero)
Oficio$Deshollinador <- as.numeric(Oficio$Deshollinador)
Oficio$Editor <- as.numeric(Oficio$Editor)
Oficio$Escritor <- as.numeric(Oficio$Escritor)
Oficio$Escultor <- as.numeric(Oficio$Escultor)
Oficio$Exterminador <- as.numeric(Oficio$Exterminador)
Oficio$Plomero <- as.numeric(Oficio$Plomero)
Oficio$Impresor <- as.numeric(Oficio$Impresor)
Oficio$Lavandero <- as.numeric(Oficio$Lavandero)
Oficio$Lechero <- as.numeric(Oficio$Lechero)
Oficio$Leñador <- as.numeric(Oficio$Leñador)
Oficio$Locutor <- as.numeric(Oficio$Locutor)
Oficio$Mecanico <- as.numeric(Oficio$Mecanico)
Oficio$Obrero <- as.numeric(Oficio$Obrero)
Oficio$Panadero <- as.numeric(Oficio$Panadero)
Oficio$`Pastor ganadero` <- as.numeric(Oficio$`Pastor ganadero`)
Oficio$Peletero <- as.numeric(Oficio$Peletero)
Oficio$Peluquero <- as.numeric(Oficio$Peluquero)
Oficio$Pescador <- as.numeric(Oficio$Pescador)
Oficio$Pintor <- as.numeric(Oficio$Pintor)
Oficio$Policia <- as.numeric(Oficio$Policia)
Oficio$Repartidor <- as.numeric(Oficio$Repartidor)
Oficio$Sastre <- as.numeric(Oficio$Sastre)
Oficio$Soldador <- as.numeric(Oficio$Soldador)
Oficio$Tornero <- as.numeric(Oficio$Tornero)
Oficio$Vendedor <- as.numeric(Oficio$Vendedor)
Oficio$Vigilante <- as.numeric(Oficio$Vigilante)
Oficio$Manualidades <- as.numeric(Oficio$Manualidades)

# vamos a crear subgrupos por localidad y luego se concatenan. Para esto creamos una función:
# Funcion:
# Esta función usa la data inicial y la localización que queremos usar:
AgrupaInforma <- function(Data,LocalizacionStr){
  
  DataLocaliza <- Data %>% 
  dplyr::filter(Localizacion==LocalizacionStr)

  DataLocaliza_v2 <- data.frame("Localizacion"=c(LocalizacionStr),
                      "Oficio"=c("Agricultor","Albañil","Animador","Artesano","Barbero","Barrendero","Cajero","Carnicero","Carpintero","Cerrajero","Conductor","Cocinero","Deshollinador","Editor","Escritor","Escultor","Exterminador","Plomero","Impresor","Lavandero","Lechero","Leñador","Locutor","Mecánico","Obrero","Panadero","Pastor ganadero","Peletero","Peluquero","Pescador","Pintor","Policía","Repartidor","Sastre","Soldador","Tornero","Vendedor","Vigilante","Manualidades"),
                      "Subtotal"=colSums(DataLocaliza[,2:40], na.rm=T)
                        )

  DataLocaliza_v2$Total <- sum(DataLocaliza_v2$Subtotal)

  DataLocaliza_v2 <- DataLocaliza_v2 %>% 
  dplyr::mutate(Porcentaje=round((Subtotal/Total)*100,2))

return(DataLocaliza_v2)
}

# Aplicamos la función en cada localización:
Cabecera <- AgrupaInforma(Data=Oficio,LocalizacionStr="Cabecera Urbana")
VdaGuacamayal <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Guacamayal")
VdaVinia <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda La Viña")
VdaPalenque <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Palenque")
VdaPalenquito <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Palenquito")
VdaQuebraAlta <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Quebradona Alta")
VdaQuebraBaja <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Quebradona Baja")
VdaQuebraMedia <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Quebradona Media")
CorrPaloCabil <- AgrupaInforma(Data=Oficio,LocalizacionStr="Corregimiento de Palocabildo")
VdaVallecitos <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Vallecitos")
VdaHermosa <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda La Hermosa")
VdaPista <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda La Pista")
VdaCabania <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda La Cabaña")
VdaBuga <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Buga")
VdaCauca <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda Cauca")
VdaLaFe <- AgrupaInforma(Data=Oficio,LocalizacionStr="Vereda La Fe")
CorrPteIgle <- AgrupaInforma(Data=Oficio,LocalizacionStr="Corregimiento de Puente Iglesias")

# Concatenamos la data:
Oficio_v2 <- join_all(list(Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebraAlta,VdaQuebraBaja,VdaQuebraMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPteIgle), by=c("Localizacion"),type = "full")

Oficio_v2 <- Oficio_v2 %>% 
  dplyr::filter(Porcentaje!=0.00)

# Gráfico: No se realiza debido a la complejidad de visualización.

# Paso opcional: exportamos data:
write_xlsx(Oficio_v2, "Oficio.xlsx")

# Eliminamos intermedios:
rm(Oficio,Oficio_v2,Cabecera,VdaVinia,VdaPalenque,VdaGuacamayal,VdaPalenquito,VdaQuebraAlta,VdaQuebraBaja,VdaQuebraMedia,CorrPaloCabil,VdaVallecitos,VdaHermosa,VdaPista,VdaCabania,VdaBuga,VdaCauca,VdaLaFe,CorrPteIgle,AgrupaInforma)
```

```{r Modulo Proyectos productivos}
#### Tema: Tiene proyecto productivo ####
# Pregunta data: "¿Tiene este hogar algún tipo de negocio?"

Proyecto <- PilotoHogares %>%
  dplyr::select(Localizacion,"¿Tiene este hogar algún tipo de negocio?") %>%
  dplyr::rename(ProyectoCol="¿Tiene este hogar algún tipo de negocio?")%>%  dplyr::filter(ProyectoCol!="No responde",
                        is.na(ProyectoCol)==F) 

Proyecto_v2 <- Agrupa(Data=Proyecto,
                 Columna=ProyectoCol)

# Graficamos:

ggplot(Proyecto_v2, aes(x=Porcentaje,y=Localizacion,fill=ProyectoCol))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Proyectos productivos en el hogar:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Proyecto_v2, "Negocio.xlsx")

# Eliminamos intermedios:
rm(Proyecto,Proyecto_v2)


#### Tema: Sector económico del proyecto ####
# Pregunta data: "¿Cuál es la actividad económica del negocio?"

Actividad <- PilotoProyectos %>%
  dplyr::select(Localizacion,"¿Cuál es la actividad económica del negocio?") %>%
  dplyr::rename(Sector="¿Cuál es la actividad económica del negocio?") %>% 
  dplyr::filter(Sector!="No responde")

# Recodificamos variables:
Actividad$SectorShort <- c("Sector")

Actividad <- Actividad %>% 
  dplyr::mutate(SectorShort=ifelse(Sector=="A-Agricultura, Ganadería, Caza, Silvicultura y Pesca","A-Agricultura",SectorShort),
                SectorShort=ifelse(Sector=="C-Industrias manufactureras","C-Industrias manufactureras",SectorShort),
                SectorShort=ifelse(Sector=="H-Transporte y almacenamiento","H-Transporte y almacenamiento",SectorShort),
                SectorShort=ifelse(Sector=="G-Comercio al por mayor y por menor; reparación de vehículos y motos","G-Comercio",SectorShort),
                SectorShort=ifelse(Sector=="T-Actividades de hogares individuales.","T-Actividades de hogares",SectorShort),
                SectorShort=ifelse(Sector=="F-Construcción","F-Construcción",SectorShort),
                SectorShort=ifelse(Sector=="P-Educación","P-Educación",SectorShort),
                SectorShort=ifelse(Sector=="Q-Actividades de atención de la salud humana y asistencia social","Q-Salud humana y asistencia social",SectorShort),
                SectorShort=ifelse(Sector=="S-Otras actividades de servicios","S-Otros servicios",SectorShort),
                SectorShort=ifelse(Sector=="J-Información y comunicaciones","J-Información y comunicaciones",SectorShort),
                SectorShort=ifelse(Sector=="N-Actividades de servicio administrativo y de apoyo","N-Actividades administrativas y de apoyo",SectorShort),
                SectorShort=ifelse(Sector=="I-Alojamiento y servicios de comida","I-Alojamiento y comida",SectorShort),
                SectorShort=ifelse(Sector=="R-Actividades Artisticas, de entretenimiento y recreación.","R-Actividades Artisticas y recreación",SectorShort),
                SectorShort=ifelse(Sector=="K-Actividades financieras y de seguros","K-Actividades financieras",SectorShort),
                SectorShort=ifelse(Sector=="B-Explotación de Minas y canteras","B-Explotación de Minas",SectorShort),
                SectorShort=ifelse(Sector=="M-Actividades profesionales, científicas y técnicas","M-Actividades profesionales",SectorShort),
                SectorShort=ifelse(Sector=="D-Suministro de electricidad, gas, vapor y aire acondicionado","D-Suministro de electricidad",SectorShort),
                SectorShort=ifelse(Sector=="E-Distribución de agua, evacuación y tratamiento de residuos; gestión de desechos y saneamiento","E-Distribución de agua",SectorShort),
                SectorShort=ifelse(Sector=="O-Administración pública y defensa","O-Administración pública",SectorShort),
                )


# Agrupamos como corresponde:
Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=SectorShort)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=SectorShort))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Sector económico del negocio:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "SectorNegocio.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Inscrito en CC ####
# Pregunta data: "¿Está inscrito en Cámara de Comercio?"

Actividad <- PilotoProyectos %>%
  dplyr::select(Localizacion,"¿Está inscrito en Cámara de Comercio?") %>%
  dplyr::rename(Inscripcion="¿Está inscrito en Cámara de Comercio?") %>% 
  dplyr::filter(Inscripcion!="No sabe")

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Inscripcion)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Inscripcion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Inscripción en Cámara de Comercio:")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "CCNegocio.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)

#### Tema: Tiene RUT ####
# Pregunta data: "¿Tiene Rut?"

Actividad <- PilotoProyectos %>%
  dplyr::select(Localizacion,"¿Tiene Rut?") %>%
  dplyr::rename(Inscripcion="¿Tiene Rut?") %>% 
  dplyr::filter(Inscripcion!="No sabe")

Actividad_v2 <- Agrupa(Data=Actividad,
                 Columna=Inscripcion)

# Graficamos:

ggplot(Actividad_v2, aes(x=Porcentaje,y=Localizacion,fill=Inscripcion))+
  geom_bar(stat="identity", position="dodge")+
  labs(x="Porcentaje",y="Localización",fill="Inscripción en Registro Único Tributario (RUT):")+
  geom_text(aes(label = Porcentaje),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_x_continuous(limits=c(0,105))

# Paso opcional: exportamos data:
write_xlsx(Actividad_v2, "RUTNegocio.xlsx")

# Eliminamos intermedios:
rm(Actividad,Actividad_v2)


#### Tema: Promedio de ingresos ####
# Pregunta data: "¿Cuál fue la ganancia neta en esta actividad el mes pasado?"

Proyectos <- PilotoProyectos %>%
  dplyr::select(Localizacion,"¿Cuál fue la ganancia neta en esta actividad el mes pasado?") %>%
  dplyr::rename(Ingresos="¿Cuál fue la ganancia neta en esta actividad el mes pasado?") %>% 
  dplyr::filter(Ingresos>0)

# Transformamos data a tipo numérico
Proyectos$Ingresos <- as.numeric(Proyectos$Ingresos)

# Creamos DF: con promedios de ganancia por localización:

Ganancia <- Proyectos %>% 
  dplyr::group_by(Localizacion)%>%
    dplyr::summarise(
      "Ganancia del negocio" = round(mean(Ingresos,na.rm = TRUE),0)
      )

# Graficamos:
ggplot(Ganancia, aes(x=`Ganancia del negocio`,y=Localizacion))+
  geom_bar(stat="identity", position="dodge",fill="cyan4")+
  labs(x="Ganancia del negocio (promedio) ",y="Localización")+
  geom_text(aes(label = `Ganancia del negocio`),position = position_dodge(1),
            size=4, vjust=0.6, hjust=0 ,col="black")+
  theme(axis.title=element_text(size=rel(1.3)),
        axis.text.x=element_text(size=rel(1.3)),
        axis.text.y=element_text(size=rel(1.3)),
        legend.title=element_text(size=rel(1.1)),
        legend.text=element_text(size=rel(1)),
        legend.position="top",
        legend.direction = "vertical")+
  scale_fill_brewer(palette=1)+
  scale_x_continuous(limits=c(0,1300000))


# Paso opcional: exportamos data:
write_xlsx(Ganancia, "GananciaNegocio.xlsx")

# Eliminamos intermedios:
rm(Proyectos,Ganancia)

```

## Eliminación de intermedios
```{r pruebas, include=FALSE}
rm(Vivienda,Vivienda_v2)
# Evitemos la notación científica:
 options(scipen=999)
# Para volver a notación cientifica:
# options(scipen=0)
urbano <-IngresosJerico %>% 
  dplyr::filter(.,Zona==1 & P_021>=12)
rural <-  IngresosJerico %>% 
  dplyr::filter(.,Zona==2 & P_021>=10)

 
```









